#!/usr/bin/env tsx
/**
 * build-design-packs.ts
 *
 * Scans a directory of design-pack YAML files and generates a TypeScript
 * module exporting all packs as a typed array.
 *
 * Usage:
 *   tsx scripts/build-design-packs.ts --source <path-to-examples>
 *
 * Resolution order for source path:
 *   1. --source CLI argument
 *   2. DESIGN_PACKS_SOURCE environment variable
 *   3. ../../tooling/examples/ relative to this script
 */

import * as fs from 'fs'
import * as path from 'path'
import { fileURLToPath } from 'url'
import * as yaml from 'js-yaml'
import type { DesignPack, PackMeta, Requirements, Proposal, Scenario, Evaluation } from '../src/design/types'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

// ---------------------------------------------------------------------------
// CLI arg parsing
// ---------------------------------------------------------------------------

function resolveSource(): string {
  const args = process.argv.slice(2)
  const srcIdx = args.indexOf('--source')
  if (srcIdx !== -1 && args[srcIdx + 1]) {
    return path.resolve(args[srcIdx + 1])
  }
  if (process.env.DESIGN_PACKS_SOURCE) {
    return path.resolve(process.env.DESIGN_PACKS_SOURCE)
  }
  // Default: ../../tooling/examples relative to this script
  return path.resolve(__dirname, '..', '..', 'tooling', 'examples')
}

// ---------------------------------------------------------------------------
// YAML helpers
// ---------------------------------------------------------------------------

function readYaml<T>(filePath: string): T {
  const raw = fs.readFileSync(filePath, 'utf-8')
  return yaml.load(raw) as T
}

function tryReadYaml<T>(filePath: string): T | null {
  if (!fs.existsSync(filePath)) return null
  return readYaml<T>(filePath)
}

// ---------------------------------------------------------------------------
// Pack extraction
// ---------------------------------------------------------------------------

function isMultiService(dirName: string, req: any): boolean {
  if (dirName.includes('multiservice')) return true
  if (req.services && Array.isArray(req.services) && req.services.length > 1) return true
  if (req.scale?.shape_preference?.includes('multi')) return true
  return false
}

function truncate(text: string, maxLen: number = 200): string {
  const cleaned = text.replace(/\s+/g, ' ').trim()
  if (cleaned.length <= maxLen) return cleaned
  return cleaned.slice(0, maxLen - 3) + '...'
}

function buildPack(dirPath: string): DesignPack | null {
  const dirName = path.basename(dirPath)

  const reqPath = path.join(dirPath, 'requirements.yaml')
  const scenPath = path.join(dirPath, 'scenario.yaml')

  if (!fs.existsSync(reqPath) || !fs.existsSync(scenPath)) {
    return null
  }

  const requirements = readYaml<Requirements>(reqPath)
  const scenario = readYaml<Scenario>(scenPath)
  const proposal = tryReadYaml<Proposal>(path.join(dirPath, 'proposal.yaml'))
  const evaluation = tryReadYaml<Evaluation>(path.join(dirPath, 'evaluation.yaml'))

  const meta: PackMeta = {
    id: dirName,
    name: (requirements as any).system?.name ?? (scenario as any).scenario?.name ?? dirName,
    domain: (requirements as any).system?.domain ?? 'unknown',
    category: (scenario as any).scenario?.category ?? 'unknown',
    narrative: truncate((scenario as any).scenario?.narrative ?? ''),
    result: (evaluation as any)?.evaluation?.result ?? null,
    isMultiService: isMultiService(dirName, requirements),
  }

  return { meta, requirements, proposal, scenario, evaluation }
}

// ---------------------------------------------------------------------------
// Code generation
// ---------------------------------------------------------------------------

function generateModule(packs: DesignPack[]): string {
  const lines: string[] = []
  lines.push('// AUTO-GENERATED by scripts/build-design-packs.ts — do not edit by hand')
  lines.push('')
  lines.push("import type { DesignPack } from '../types'")
  lines.push('')
  lines.push(`export const PACKS: DesignPack[] = ${JSON.stringify(packs, null, 2)}`)
  lines.push('')
  return lines.join('\n')
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function main() {
  const source = resolveSource()
  console.log(`[build-design-packs] source: ${source}`)

  if (!fs.existsSync(source)) {
    console.error(`[build-design-packs] ERROR: source path does not exist: ${source}`)
    process.exit(1)
  }

  const entries = fs.readdirSync(source, { withFileTypes: true })
    .filter(e => e.isDirectory())
    .sort((a, b) => a.name.localeCompare(b.name))

  const packs: DesignPack[] = []
  for (const entry of entries) {
    const pack = buildPack(path.join(source, entry.name))
    if (pack) {
      packs.push(pack)
      console.log(`  + ${pack.meta.id} (${pack.meta.result ?? 'no evaluation'})`)
    } else {
      console.log(`  - ${entry.name} (skipped — missing requirements.yaml or scenario.yaml)`)
    }
  }

  const outDir = path.resolve(__dirname, '..', 'src', 'design', 'data')
  fs.mkdirSync(outDir, { recursive: true })

  const outPath = path.join(outDir, 'packs.generated.ts')
  fs.writeFileSync(outPath, generateModule(packs), 'utf-8')

  console.log(`\n[build-design-packs] wrote ${packs.length} packs to ${outPath}`)
}

main()
