package generator

import (
	"fmt"
	"path/filepath"
	"runtime"
	"strings"
)

const anipCSharpPackageVersion = "0.24.7"

func BuildCSharpProject(definition *AnipServiceDefinition, options BuildCSharpProjectOptions) (*GeneratedProject, error) {
	model, err := BuildGenerationModel(definition)
	if err != nil {
		return nil, err
	}
	if options.DependencySource == "" {
		options.DependencySource = DependencySourceRegistry
	}
	transports, err := normalizeTransports(options.Transports)
	if err != nil {
		return nil, err
	}
	if options.Port == 0 {
		options.Port = defaultGeneratorPort
	}

	projectName := strings.TrimSpace(options.ProjectName)
	if projectName == "" {
		projectName = csharpProjectName(model.SystemName)
	}
	rootNamespace := strings.TrimSpace(options.RootNamespace)
	if rootNamespace == "" {
		rootNamespace = csharpNamespace(projectName)
	}
	if err := validateDependencySource(options.DependencySource); err != nil {
		return nil, err
	}
	if err := validateGeneratedPort(options.Port); err != nil {
		return nil, err
	}
	if err := validateCSharpProjectName(projectName); err != nil {
		return nil, err
	}
	if err := validateCSharpNamespace(rootNamespace); err != nil {
		return nil, err
	}
	testsProjectName := projectName + ".Tests"

	files := []GeneratedFile{
		{Path: projectName + ".csproj", Content: buildGeneratedCSharpProjectFile(options.DependencySource, transports)},
		{Path: "README.md", Content: buildGeneratedCSharpReadme(model.SystemName, options.DependencySource, transports)},
		{Path: "appsettings.json", Content: buildGeneratedCSharpAppSettings(options.Port)},
		{Path: "anip-service-definition.json", Content: string(model.DefinitionJSON)},
		{Path: "Program.cs", Content: buildGeneratedCSharpProgram(rootNamespace, model.SystemName, transports)},
		{Path: "GeneratedRuntimeTarget.cs", Content: buildGeneratedCSharpRuntimeTarget(rootNamespace, string(model.RuntimeTargetJSON), string(model.CapabilitiesJSON), fallbackString(definition.ContractSchemaVersion, "generated-1"))},
		{Path: "BackendAdapter.cs", Content: buildGeneratedCSharpBackendAdapter(rootNamespace)},
		{Path: "Policy.cs", Content: buildGeneratedCSharpPolicy(rootNamespace)},
		{Path: "GeneratedCapabilities.cs", Content: buildGeneratedCSharpCapabilities(rootNamespace)},
		{Path: filepath.ToSlash(filepath.Join("tests", testsProjectName+".csproj")), Content: buildGeneratedCSharpTestsProjectFile(projectName, options.DependencySource)},
		{Path: filepath.ToSlash(filepath.Join("tests", "GeneratedCapabilitiesTests.cs")), Content: buildGeneratedCSharpTests(rootNamespace, firstGeneratedCapabilityID(model))},
	}
	files = append(files, buildIntegrationFrontingArtifacts(model)...)
	project := &GeneratedProject{
		PackageName: projectName,
		SystemName:  model.SystemName,
		Transports:  TransportNames(transports),
		CustomBundleTemplateValues: map[string]string{
			"CSHARP_ROOT_NAMESPACE": rootNamespace,
			"PACKAGE_NAME":          projectName,
		},
		Files: files,
	}
	return project, nil
}

func buildGeneratedCSharpProjectFile(dependencySource DependencySource, transports []Transport) string {
	lines := []string{
		`<Project Sdk="Microsoft.NET.Sdk.Web">`,
		`  <PropertyGroup>`,
		`    <TargetFramework>net10.0</TargetFramework>`,
		`    <Nullable>enable</Nullable>`,
		`    <ImplicitUsings>enable</ImplicitUsings>`,
		`  </PropertyGroup>`,
		"",
		`  <ItemGroup>`,
		`    <Compile Remove="tests/**/*.cs" />`,
		`    <None Include="tests/**/*.cs" />`,
		`  </ItemGroup>`,
		"",
	}
	if dependencySource == DependencySourceLocal {
		lines = append(lines, `  <ItemGroup>`)
		for _, reference := range []string{
			"Anip.Core/Anip.Core.csproj",
			"Anip.Crypto/Anip.Crypto.csproj",
			"Anip.Server/Anip.Server.csproj",
			"Anip.Service/Anip.Service.csproj",
			"Anip.AspNetCore/Anip.AspNetCore.csproj",
			"Anip.Rest.AspNetCore/Anip.Rest.AspNetCore.csproj",
			"Anip.GraphQL.AspNetCore/Anip.GraphQL.AspNetCore.csproj",
			"Anip.Mcp.AspNetCore/Anip.Mcp.AspNetCore.csproj",
		} {
			lines = append(lines, `    <ProjectReference Include="`+localCSharpProjectReference(reference)+`" />`)
		}
		if hasTransport(transports, TransportStdio) {
			lines = append(lines, `    <ProjectReference Include="`+localCSharpProjectReference("Anip.Stdio/Anip.Stdio.csproj")+`" />`)
		}
		lines = append(lines, `  </ItemGroup>`, "")
	} else {
		lines = append(lines,
			`  <PropertyGroup>`,
			`    <AnipVersion>`+anipCSharpPackageVersion+`</AnipVersion>`,
			`  </PropertyGroup>`,
			`  <ItemGroup>`,
			`    <PackageReference Include="Anip.Core" Version="$(AnipVersion)" />`,
			`    <PackageReference Include="Anip.Crypto" Version="$(AnipVersion)" />`,
			`    <PackageReference Include="Anip.Server" Version="$(AnipVersion)" />`,
			`    <PackageReference Include="Anip.Service" Version="$(AnipVersion)" />`,
			`    <PackageReference Include="Anip.AspNetCore" Version="$(AnipVersion)" />`,
			`    <PackageReference Include="Anip.Rest.AspNetCore" Version="$(AnipVersion)" />`,
			`    <PackageReference Include="Anip.GraphQL.AspNetCore" Version="$(AnipVersion)" />`,
			`    <PackageReference Include="Anip.Mcp.AspNetCore" Version="$(AnipVersion)" />`,
		)
		if hasTransport(transports, TransportStdio) {
			lines = append(lines, `    <PackageReference Include="Anip.Stdio" Version="$(AnipVersion)" />`)
		}
		lines = append(lines, `  </ItemGroup>`, "")
	}
	lines = append(lines, `</Project>`, "")
	return strings.Join(lines, "\n")
}

func buildGeneratedCSharpTestsProjectFile(projectName string, dependencySource DependencySource) string {
	lines := []string{
		`<Project Sdk="Microsoft.NET.Sdk">`,
		`  <PropertyGroup>`,
		`    <TargetFramework>net10.0</TargetFramework>`,
		`    <Nullable>enable</Nullable>`,
		`    <ImplicitUsings>enable</ImplicitUsings>`,
		`    <IsPackable>false</IsPackable>`,
		`  </PropertyGroup>`,
		"",
		`  <ItemGroup>`,
		`    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />`,
		`    <PackageReference Include="xunit" Version="2.9.2" />`,
		`    <PackageReference Include="xunit.runner.visualstudio" Version="3.0.1">`,
		`      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>`,
		`      <PrivateAssets>all</PrivateAssets>`,
		`    </PackageReference>`,
		`  </ItemGroup>`,
		"",
		`  <ItemGroup>`,
		`    <ProjectReference Include="../` + projectName + `.csproj" />`,
		`  </ItemGroup>`,
	}
	if dependencySource == DependencySourceLocal {
		lines = append(lines,
			"",
			`  <ItemGroup>`,
			`    <ProjectReference Include="`+localCSharpProjectReference("Anip.Core/Anip.Core.csproj")+`" />`,
			`    <ProjectReference Include="`+localCSharpProjectReference("Anip.Service/Anip.Service.csproj")+`" />`,
			`  </ItemGroup>`,
		)
	}
	lines = append(lines, "", `</Project>`, "")
	return strings.Join(lines, "\n")
}

func buildGeneratedCSharpReadme(systemName string, dependencySource DependencySource, transports []Transport) string {
	lines := []string{
		"# " + titleCase(strings.NewReplacer("-", " ", "_", " ").Replace(systemName)),
		"",
		"Generated by `anip generate --target csharp` from an exported `anip-service-definition.json`.",
		"",
		"## What is generated",
		"",
		"- ASP.NET Core ANIP host using the repo's `Anip.*` runtime packages",
		"- generated capability declarations from the shared Go generation model",
		"- explicit backend adapter and policy seams for handwritten completion",
		"- xUnit smoke test covering capability generation",
		"",
		"## Commands",
		"",
	}
	if dependencySource == DependencySourceLocal {
		lines = append(lines,
			"- `dotnet run --project ./"+csharpProjectName(systemName)+".csproj`",
			"- `dotnet test ./tests/"+csharpProjectName(systemName)+".Tests.csproj`",
		)
	} else {
		lines = append(lines,
			"- `dotnet run --project ./"+csharpProjectName(systemName)+".csproj`",
			"- `dotnet test ./tests/"+csharpProjectName(systemName)+".Tests.csproj`",
		)
	}
	if hasTransport(transports, TransportStdio) {
		lines = append(lines, "- `dotnet run --project ./"+csharpProjectName(systemName)+".csproj -- --stdio`")
	}
	lines = append(lines, "")
	return strings.Join(lines, "\n")
}

func buildGeneratedCSharpAppSettings(port int) string {
	return strings.Join([]string{
		"{",
		`  "Urls": "http://0.0.0.0:` + fmt.Sprintf("%d", port) + `"`,
		"}",
		"",
	}, "\n")
}

func buildGeneratedCSharpProgram(namespaceName, systemName string, transports []Transport) string {
	lines := []string{
		"using Anip.AspNetCore;",
		"using Anip.GraphQL.AspNetCore;",
		"using Anip.Mcp.AspNetCore;",
		"using Anip.Rest.AspNetCore;",
		"using Anip.Service;",
	}
	if hasTransport(transports, TransportStdio) {
		lines = append(lines, "using Anip.Stdio;")
	}
	lines = append(lines,
		"using System.Text.Json;",
		"using "+namespaceName+";",
		"",
		"var builder = WebApplication.CreateBuilder(args);",
		`var bindUrl = Environment.GetEnvironmentVariable("ASPNETCORE_URLS")`,
		`    ?? Environment.GetEnvironmentVariable("ANIP_HTTP_URL")`,
		`    ?? builder.Configuration["Urls"]`,
		`    ?? "http://0.0.0.0:4100";`,
		"builder.WebHost.UseUrls(bindUrl);",
		"",
		"var apiKeys = ApiKeys();",
		`var serviceId = Environment.GetEnvironmentVariable("ANIP_SERVICE_ID") ?? "`+systemName+`";`,
		`var serviceFilter = Environment.GetEnvironmentVariable("ANIP_SERVICE_FILTER") ?? serviceId;`,
		"",
		"var service = new AnipService(new ServiceConfig",
		"{",
		"    ServiceId = serviceId,",
		"    Capabilities = GeneratedCapabilities.CreateAll(BackendAdapter.Default, serviceFilter),",
		`    Storage = Environment.GetEnvironmentVariable("ANIP_STORAGE") ?? ":memory:",`,
		`    Trust = Environment.GetEnvironmentVariable("ANIP_TRUST_LEVEL") ?? "signed",`,
		`    KeyPath = Environment.GetEnvironmentVariable("ANIP_KEY_PATH") ?? "./anip-keys",`,
		`    Authenticate = bearer => apiKeys.TryGetValue(bearer, out var principal) ? principal : null,`,
		"});",
		"",
	)
	if hasTransport(transports, TransportStdio) {
		lines = append(lines,
			`if (args.Contains("--stdio"))`,
			"{",
			"    await AnipStdioRunner.RunAsync(service);",
			"    return;",
			"}",
			"",
		)
	}
	lines = append(lines,
		"builder.Services.AddAnip(service);",
		"builder.Services.AddAnipMcp(service);",
		"builder.Services.AddControllers()",
		"    .AddApplicationPart(typeof(AnipRestController).Assembly)",
		"    .AddApplicationPart(typeof(AnipGraphQLController).Assembly);",
		"",
		"var app = builder.Build();",
		"app.MapControllers();",
		"app.MapAnipMcp();",
		"app.Run();",
		"",
		"static Dictionary<string, string> ApiKeys()",
		"{",
		`    var raw = Environment.GetEnvironmentVariable("ANIP_API_KEYS_JSON");`,
		"    if (string.IsNullOrWhiteSpace(raw))",
		"    {",
		"        return new Dictionary<string, string>",
		"        {",
		`            ["demo-human-key"] = "human:generated",`,
		`            ["demo-agent-key"] = "agent:generated-service",`,
		"        };",
		"    }",
		"    try",
		"    {",
		"        var decoded = JsonSerializer.Deserialize<Dictionary<string, object?>>(raw) ?? [];",
		"        var result = new Dictionary<string, string>();",
		"        foreach (var entry in decoded)",
		"        {",
		"            if (!string.IsNullOrWhiteSpace(entry.Key) && entry.Value is not null)",
		"            {",
		"                result[entry.Key] = entry.Value.ToString() ?? string.Empty;",
		"            }",
		"        }",
		`        return result.Count == 0 ? new Dictionary<string, string> { ["demo-agent-key"] = "agent:generated-service" } : result;`,
		"    }",
		"    catch",
		"    {",
		`        return new Dictionary<string, string> { ["demo-agent-key"] = "agent:generated-service" };`,
		"    }",
		"}",
		"",
	)
	return strings.Join(lines, "\n")
}

func buildGeneratedCSharpRuntimeTarget(namespaceName, runtimeTargetJSON, capabilityMetadataJSON, contractVersion string) string {
	return strings.Join([]string{
		"using System.Text.Json;",
		"",
		"namespace " + namespaceName + ";",
		"",
		"public static class GeneratedRuntimeTarget",
		"{",
		"    public static string ContractVersion => " + csharpQuoted(contractVersion) + ";",
		"",
		"    public static Dictionary<string, object?> RuntimeTarget { get; } =",
		`        JsonSerializer.Deserialize<Dictionary<string, object?>>(RuntimeTargetJson)!;`,
		"",
		"    public static List<Dictionary<string, object?>> Capabilities { get; } =",
		`        JsonSerializer.Deserialize<List<Dictionary<string, object?>>>(CapabilityMetadataJson)!;`,
		"",
		"    public const string RuntimeTargetJson = \"\"\"",
		runtimeTargetJSON + "\"\"\";",
		"",
		"    private const string CapabilityMetadataJson = \"\"\"",
		capabilityMetadataJSON + "\"\"\";",
		"}",
		"",
	}, "\n")
}

func buildGeneratedCSharpBackendAdapter(namespaceName string) string {
	return strings.Join([]string{
		"using Anip.Service;",
		"",
		"namespace " + namespaceName + ";",
		"",
		"public delegate Dictionary<string, object?> BackendAdapterHandler(",
		"    Dictionary<string, object?> capability,",
		"    Dictionary<string, object?> plan,",
		"    Dictionary<string, object?> adapterInput,",
		"    InvocationContext context);",
		"",
		"public static class BackendAdapter",
		"{",
		"    public static BackendAdapterHandler Default => Execute;",
		"",
		"    private static Dictionary<string, object?> Execute(",
		"        Dictionary<string, object?> capability,",
		"        Dictionary<string, object?> plan,",
		"        Dictionary<string, object?> _adapterInput,",
		"        InvocationContext _context)",
		"    {",
		"        var result = new Dictionary<string, object?>",
		"        {",
		`            ["capability_id"] = capability["capability_id"],`,
		`            ["selected_backend"] = plan["selected_binding"],`,
		`            ["semantic_input"] = plan["semantic_input"],`,
		`            ["backend_input_contract"] = plan["backend_input_contract"],`,
		"        };",
		"",
		`        var unresolved = GeneratedCapabilities.StringList(plan.GetValueOrDefault("unresolved_required_backend_inputs"));`,
		"        if (unresolved.Count > 0)",
		"        {",
		`            result["execution_status"] = "backend_input_incomplete";`,
		`            result["unresolved_required_backend_inputs"] = unresolved;`,
		`            result["note"] = "Generated host is runnable, but backend-only inputs still require extension completion.";`,
		"            return result;",
		"        }",
		"",
		`        var executionPosture = capability.GetValueOrDefault("execution_posture")?.ToString();`,
		`        if (executionPosture == "approval_gated")`,
		"        {",
		`            result["execution_status"] = "approval_required";`,
		`            result["title"] = capability["title"];`,
		`            result["summary"] = capability["summary"];`,
		`            result["approval_rule_refs"] = Array.Empty<string>();`,
		`            result["note"] = "Generated host requires approval before backend execution.";`,
		"            return result;",
		"        }",
		`        if (executionPosture == "prepare_only")`,
		"        {",
		`            result["execution_status"] = "prepared";`,
		`            result["note"] = "Generated host prepared a governed preview and did not execute the backend.";`,
		"            return result;",
		"        }",
		"",
		`        result["execution_status"] = "backend_execution_stub";`,
		`        result["note"] = "Replace BackendAdapter.Default with provider-specific backend execution.";`,
		"        return result;",
		"    }",
		"}",
		"",
	}, "\n")
}

func buildGeneratedCSharpPolicy(namespaceName string) string {
	return strings.Join([]string{
		"using System.Text.Json;",
		"using System.Text.Json.Serialization;",
		"",
		"namespace " + namespaceName + ";",
		"",
		"public readonly record struct PolicyDecision(string Decision, string? Detail);",
		"",
		"public sealed class PrincipalSelector",
		"{",
		`    [JsonPropertyName("claim")] public string? Claim { get; set; }`,
		`    [JsonPropertyName("equals")] public string? Equals { get; set; }`,
		"}",
		"",
		"public sealed class RuntimePolicyBinding",
		"{",
		`    [JsonPropertyName("id")] public string? Id { get; set; }`,
		`    [JsonPropertyName("actor_id")] public string? ActorId { get; set; }`,
		`    [JsonPropertyName("principal_selector")] public PrincipalSelector? PrincipalSelector { get; set; }`,
		`    [JsonPropertyName("capability_ids")] public List<string>? CapabilityIds { get; set; }`,
		`    [JsonPropertyName("decision")] public string? Decision { get; set; }`,
		`    [JsonPropertyName("business_rule")] public string? BusinessRule { get; set; }`,
		`    [JsonPropertyName("enforcement_notes")] public string? EnforcementNotes { get; set; }`,
		"}",
		"",
		"public sealed class RuntimePolicyTarget",
		"{",
		`    [JsonPropertyName("policy_bindings")] public List<RuntimePolicyBinding>? PolicyBindings { get; set; }`,
		"}",
		"",
		"public static class Policy",
		"{",
		"    private static readonly List<RuntimePolicyBinding> PolicyBindings =",
		"        JsonSerializer.Deserialize<RuntimePolicyTarget>(GeneratedRuntimeTarget.RuntimeTargetJson)?.PolicyBindings ?? [];",
		"",
		"    public static PolicyDecision Evaluate(",
		"        Dictionary<string, object?> capability,",
		"        Dictionary<string, object?> parameters,",
		"        string? rootPrincipal)",
		"    {",
		`        var capabilityId = StringValue(capability, "capability_id");`,
		"        var bindings = PolicyBindings.Where(binding => binding.CapabilityIds?.Contains(capabilityId) == true).ToList();",
		`        if (bindings.Count == 0) return new PolicyDecision("allow", null);`,
		"        var claims = PrincipalClaims(rootPrincipal);",
		`        if (claims.Count == 0) return new PolicyDecision("allow", null);`,
		"        var matching = bindings.Where(binding => MatchesPrincipal(binding, claims)).ToList();",
		"        if (RequiresGovernedStop(capability))",
		"        {",
		`            var denied = matching.FirstOrDefault(binding => binding.Decision == "deny");`,
		"            if (denied is not null) return DecisionFor(denied);",
		`            var approval = matching.FirstOrDefault(binding => binding.Decision == "approval_required");`,
		"            if (approval is not null) return DecisionFor(approval);",
		`            var clarify = matching.FirstOrDefault(binding => binding.Decision == "clarify");`,
		"            if (clarify is not null) return DecisionFor(clarify);",
		"        }",
		`        var allowed = matching.FirstOrDefault(binding => binding.Decision != "deny" && binding.Decision != "clarify" && binding.Decision != "approval_required");`,
		"        if (allowed is not null) return DecisionFor(allowed);",
		`        return new PolicyDecision("allow", "No matching runtime policy binding; continuing.");`,
		"    }",
		"",
		"    private static bool RequiresGovernedStop(Dictionary<string, object?> capability)",
		"    {",
		`        return capability.GetValueOrDefault("grant_policy") is JsonElement { ValueKind: JsonValueKind.Object } grantPolicy && grantPolicy.EnumerateObject().Any()`,
		`            || StringValue(capability, "side_effect_level") == "approval_required"`,
		`            || StringValue(capability, "execution_posture") == "approval_required"`,
		`            || StringValue(capability, "operation_type") == "approval_gated";`,
		"    }",
		"",
		"    private static PolicyDecision DecisionFor(RuntimePolicyBinding binding)",
		"    {",
		`        var decision = FirstNonEmpty(binding.Decision, "allow")!;`,
		"        var detail = FirstNonEmpty(binding.BusinessRule, binding.EnforcementNotes);",
		`        if (decision == "deny" || decision == "clarify" || decision == "approval_required")`,
		"        {",
		"            return new PolicyDecision(decision, detail);",
		"        }",
		`        return new PolicyDecision("allow", detail);`,
		"    }",
		"",
		"    private static Dictionary<string, string> PrincipalClaims(string? rootPrincipal)",
		"    {",
		"        var raw = rootPrincipal?.Trim() ?? string.Empty;",
		"        if (string.IsNullOrWhiteSpace(raw)) return [];",
		"        var pieces = raw.Split('|');",
		"        var claims = new Dictionary<string, string> { [\"principal\"] = pieces.Length > 0 ? pieces[0] : string.Empty };",
		"        foreach (var piece in pieces.Skip(1))",
		"        {",
		"            var separator = piece.IndexOf('=');",
		"            if (separator < 0) continue;",
		"            claims[piece[..separator].Trim()] = piece[(separator + 1)..].Trim();",
		"        }",
		"        return claims;",
		"    }",
		"",
		"    private static bool MatchesPrincipal(RuntimePolicyBinding binding, Dictionary<string, string> claims)",
		"    {",
		`        var claim = FirstNonEmpty(binding.PrincipalSelector?.Claim, "actor_id")!;`,
		"        var expected = FirstNonEmpty(binding.PrincipalSelector?.Equals, binding.ActorId);",
		"        if (string.IsNullOrWhiteSpace(expected)) return true;",
		"        if (!claims.ContainsKey(claim)) return false;",
		"        return claims.TryGetValue(claim, out var actual) && actual == expected;",
		"    }",
		"",
		"    private static string StringValue(Dictionary<string, object?> values, string key)",
		"    {",
		"        return values.TryGetValue(key, out var value) && value is not null ? value.ToString() ?? string.Empty : string.Empty;",
		"    }",
		"",
		"    private static string? FirstNonEmpty(params string?[] values)",
		"    {",
		"        foreach (var value in values)",
		"        {",
		"            if (!string.IsNullOrWhiteSpace(value)) return value;",
		"        }",
		"        return null;",
		"    }",
		"}",
		"",
	}, "\n")
}

func buildGeneratedCSharpCapabilities(namespaceName string) string {
	return strings.Join([]string{
		"using Anip.Core;",
		"using Anip.Service;",
		"using System.Linq;",
		"using System.Text.Json;",
		"",
		"namespace " + namespaceName + ";",
		"",
		"public static class GeneratedCapabilities",
		"{",
		"",
		"    public static List<CapabilityDef> CreateAll(BackendAdapterHandler backendAdapter)",
		"    {",
		`        return CreateAll(backendAdapter, "");`,
		"    }",
		"",
		"    public static List<CapabilityDef> CreateAll(BackendAdapterHandler backendAdapter, string? serviceFilter)",
		"    {",
		`        var normalizedServiceFilter = serviceFilter?.Trim() ?? "";`,
		"        return GeneratedRuntimeTarget.Capabilities",
		`            .Where(capability => string.IsNullOrWhiteSpace(normalizedServiceFilter) || normalizedServiceFilter == StringValue(capability, "service_id"))`,
		"            .Select(capability => CreateCapability(capability, backendAdapter))",
		"            .ToList();",
		"    }",
		"",
		"    private static CapabilityDef CreateCapability(",
		"        Dictionary<string, object?> capability,",
		"        BackendAdapterHandler backendAdapter)",
		"    {",
		"        var declaration = new CapabilityDeclaration",
		"        {",
		`            Name = StringValue(capability, "capability_id"),`,
		`            Description = FirstNonEmpty(StringValue(capability, "summary"), StringValue(capability, "title"), StringValue(capability, "capability_id")) ?? string.Empty,`,
		`            ContractVersion = GeneratedRuntimeTarget.ContractVersion,`,
		"            Inputs = BuildInputs(capability),",
		"            Output = new CapabilityOutput",
		"            {",
		`                Type = FirstNonEmpty(StringValue(capability, "output_shape"), "governed_result") ?? "governed_result",`,
		`                Fields = ["execution_status", "capability_id", "semantic_input", "backend_input_contract", "note"],`,
		"            },",
		"            SideEffect = new SideEffect",
		"            {",
		`                Type = SideEffectType(StringValue(capability, "side_effect_level")),`,
		`                RollbackWindow = RollbackWindowFor(StringValue(capability, "side_effect_level")),`,
		"            },",
		`            MinimumScope = StringList(capability.GetValueOrDefault("minimum_scope")),`,
		`            ResponseModes = ["unary"],`,
		`            RefreshVia = [],`,
		`            VerifyVia = [],`,
		`            Kind = DeclarationKind(capability),`,
		`            Composition = DeclarationComposition(capability),`,
		`            GrantPolicy = DeserializeModel<GrantPolicy>(capability.GetValueOrDefault("grant_policy")),`,
		"        };",
		"",
		"        return new CapabilityDef(declaration, (ctx, parameters) =>",
		"            Handle(capability, ctx, parameters, backendAdapter));",
		"    }",
		"",
		"    private static T? DeserializeModel<T>(object? value)",
		"    {",
		"        if (value is null) return default;",
		"        return JsonSerializer.Deserialize<T>(JsonSerializer.Serialize(value));",
		"    }",
		"",
		"    private static string DeclarationKind(Dictionary<string, object?> capability)",
		"    {",
		`        var kind = FirstNonEmpty(StringValue(capability, "kind"), "atomic")!;`,
		"        return kind;",
		"    }",
		"",
		"    private static Composition? DeclarationComposition(Dictionary<string, object?> capability)",
		"    {",
		`        return DeserializeModel<Composition>(capability.GetValueOrDefault("composition"));`,
		"    }",
		"",
		"    private static Dictionary<string, object?> Handle(",
		"        Dictionary<string, object?> capability,",
		"        InvocationContext ctx,",
		"        Dictionary<string, object?> parameters,",
		"        BackendAdapterHandler backendAdapter)",
		"    {",
		"        parameters = ApplyInputDefaults(capability, parameters);",
		"        AssertRequiredSemanticInputs(capability, parameters);",
		"        ValidateInputBehavior(capability, parameters);",
		"        var policy = Policy.Evaluate(capability, parameters, ctx.RootPrincipal);",
		`        if (policy.Decision == "deny")`,
		"        {",
		`            throw new AnipError("denied", FirstNonEmpty(policy.Detail, $"Request denied for {StringValue(capability, "capability_id")}.")!).WithResolution("contact_service_owner");`,
		"        }",
		`        if (policy.Decision == "clarify")`,
		"        {",
		`            throw new AnipError("clarification_required", FirstNonEmpty(policy.Detail, $"Clarification required for {StringValue(capability, "capability_id")}.")!).WithResolution("obtain_binding");`,
		"        }",
		"",
		"        var plan = BuildBackendInvocationPlan(capability, parameters);",
		`        if (policy.Decision == "approval_required" && string.IsNullOrWhiteSpace(ctx.ApprovalGrant))`,
		"        {",
		`            throw new AnipError("approval_required", FirstNonEmpty(policy.Detail, $"Approval required for {StringValue(capability, "capability_id")}.")!).WithResolution("request_approval");`,
		"        }",
		`        return backendAdapter(capability, plan, (Dictionary<string, object?>)plan["adapter_input"]!, ctx);`,
		"    }",
		"",
		"    private static List<CapabilityInput> BuildInputs(Dictionary<string, object?> capability)",
		"    {",
		"        var inputs = new List<CapabilityInput>();",
		`        foreach (var input in InputList(capability, "required_inputs"))`,
		"        {",
		"            inputs.Add(new CapabilityInput",
		"            {",
		`                Name = StringValue(input, "input_name"),`,
		`                Type = FirstNonEmpty(StringValue(input, "input_type"), "string")!,`,
		"                Required = true,",
		`                Default = DefaultValue(input),`,
		`                Description = FirstNonEmpty(StringValue(input, "summary"), StringValue(input, "input_name")),`,
		`                SemanticType = OptionalString(input, "semantic_type"),`,
		`                EntityReference = BoolValue(input.GetValueOrDefault("entity_reference")),`,
		`                AllowedValues = StringList(input.GetValueOrDefault("allowed_values")),`,
		`                CatalogRef = OptionalString(input, "catalog_ref"),`,
		`                InputMeanings = DeserializeModel<List<InputMeaning>>(input.GetValueOrDefault("input_meanings")) ?? [],`,
		`                Resolution = DeserializeModel<InputResolution>(input.GetValueOrDefault("resolution")),`,
		"            });",
		"        }",
		`        foreach (var input in InputList(capability, "optional_inputs"))`,
		"        {",
		"            inputs.Add(new CapabilityInput",
		"            {",
		`                Name = StringValue(input, "input_name"),`,
		`                Type = FirstNonEmpty(StringValue(input, "input_type"), "string")!,`,
		"                Required = false,",
		`                Default = DefaultValue(input),`,
		`                Description = FirstNonEmpty(StringValue(input, "summary"), StringValue(input, "input_name")),`,
		`                SemanticType = OptionalString(input, "semantic_type"),`,
		`                EntityReference = BoolValue(input.GetValueOrDefault("entity_reference")),`,
		`                AllowedValues = StringList(input.GetValueOrDefault("allowed_values")),`,
		`                CatalogRef = OptionalString(input, "catalog_ref"),`,
		`                InputMeanings = DeserializeModel<List<InputMeaning>>(input.GetValueOrDefault("input_meanings")) ?? [],`,
		`                Resolution = DeserializeModel<InputResolution>(input.GetValueOrDefault("resolution")),`,
		"            });",
		"        }",
		"        return inputs;",
		"    }",
		"",
		"    private static void AssertRequiredSemanticInputs(",
		"        Dictionary<string, object?> capability,",
		"        Dictionary<string, object?> parameters)",
		"    {",
		"        var missing = new List<string>();",
		`        foreach (var input in InputList(capability, "required_inputs"))`,
		"        {",
		`            if (!string.IsNullOrWhiteSpace(StringValue(input, "default_value"))) continue;`,
		`            var inputName = StringValue(input, "input_name");`,
		"            if (!parameters.TryGetValue(inputName, out var value) || value is null || value is string text && string.IsNullOrWhiteSpace(text))",
		"            {",
		"                missing.Add(inputName);",
		"            }",
		"        }",
		"        if (missing.Count > 0)",
		"        {",
		`            throw new AnipError("clarification_required", $"Required semantic inputs are missing for {StringValue(capability, "capability_id")}.", new Resolution`,
		"            {",
		`                Action = "obtain_binding",`,
		`                RecoveryClass = Constants.RecoveryClassForAction("obtain_binding"),`,
		`                Requires = string.Join(",", missing),`,
		"            });",
		"        }",
		"    }",
		"",
		"    private static void ValidateInputBehavior(",
		"        Dictionary<string, object?> capability,",
		"        Dictionary<string, object?> parameters)",
		"    {",
		"        foreach (var input in InputList(capability, \"required_inputs\").Concat(InputList(capability, \"optional_inputs\")))",
		"        {",
		`            var inputName = StringValue(input, "input_name");`,
		"            if (string.IsNullOrWhiteSpace(inputName)) continue;",
		"            if (!parameters.TryGetValue(inputName, out var value) || value is null || value is string text && string.IsNullOrWhiteSpace(text)) continue;",
		`            var allowedValues = StringList(input.GetValueOrDefault("allowed_values"));`,
		"            if (allowedValues.Count == 0 || allowedValues.Contains(value.ToString() ?? string.Empty)) continue;",
		`            var resolution = DictionaryValue(input.GetValueOrDefault("resolution"));`,
		`            var shouldDeny = StringValue(resolution, "mode") == "closed_values" && StringValue(resolution, "on_unresolved") == "deny";`,
		`            var action = shouldDeny ? "contact_service_owner" : "obtain_binding";`,
		`            throw new AnipError(shouldDeny ? "denied" : "clarification_required", $"Input {inputName} must use one of the declared allowed values.", new Resolution`,
		"            {",
		"                Action = action,",
		"                RecoveryClass = Constants.RecoveryClassForAction(action),",
		"                Requires = inputName,",
		"            });",
		"        }",
		"    }",
		"",
		"    private static object? DefaultValue(Dictionary<string, object?> input)",
		"    {",
		`        var value = StringValue(input, "default_value");`,
		"        return string.IsNullOrWhiteSpace(value) ? null : value;",
		"    }",
		"",
		"    private static Dictionary<string, object?> ApplyInputDefaults(Dictionary<string, object?> capability, Dictionary<string, object?> parameters)",
		"    {",
		"        var normalized = new Dictionary<string, object?>(parameters);",
		`        foreach (var input in InputList(capability, "required_inputs").Concat(InputList(capability, "optional_inputs")))`,
		"        {",
		`            var inputName = StringValue(input, "input_name");`,
		`            var defaultValue = StringValue(input, "default_value");`,
		`            var resolution = DictionaryValue(input.GetValueOrDefault("resolution"));`,
		`            if (StringValue(resolution, "on_missing") == "omit") continue;`,
		"            if (string.IsNullOrWhiteSpace(inputName) || string.IsNullOrWhiteSpace(defaultValue)) continue;",
		"            if (!normalized.TryGetValue(inputName, out var value) || value is null || value is string text && string.IsNullOrWhiteSpace(text))",
		"            {",
		"                normalized[inputName] = defaultValue;",
		"            }",
		"        }",
		"        return normalized;",
		"    }",
		"",
		"    private static Dictionary<string, object?> BuildBackendInvocationPlan(",
		"        Dictionary<string, object?> capability,",
		"        Dictionary<string, object?> parameters)",
		"    {",
		"        var selectedBinding = SelectBackendBinding(capability);",
		"        var contract = EffectiveBackendInputContract(capability, selectedBinding);",
		"        var semanticKeys = new HashSet<string>();",
		`        foreach (var input in InputList(capability, "required_inputs")) semanticKeys.Add(StringValue(input, "input_name"));`,
		`        foreach (var input in InputList(capability, "optional_inputs")) semanticKeys.Add(StringValue(input, "input_name"));`,
		"",
		"        var semanticInput = new Dictionary<string, object?>();",
		"        foreach (var entry in parameters)",
		"        {",
		"            if (semanticKeys.Contains(entry.Key))",
		"            {",
		"                semanticInput[entry.Key] = entry.Value;",
		"            }",
		"        }",
		"",
		"        var adapterKeys = new HashSet<string>(semanticKeys);",
		`        foreach (var required in StringList(contract.GetValueOrDefault("required"))) adapterKeys.Add(required);`,
		`        foreach (var optional in StringList(contract.GetValueOrDefault("optional"))) adapterKeys.Add(optional);`,
		"        var adapterInput = new Dictionary<string, object?>();",
		"        foreach (var entry in parameters)",
		"        {",
		"            if (adapterKeys.Contains(entry.Key))",
		"            {",
		"                adapterInput[entry.Key] = entry.Value;",
		"            }",
		"        }",
		"",
		"        var unresolved = new List<string>();",
		`        foreach (var required in StringList(contract.GetValueOrDefault("required")))`,
		"        {",
		"            if (!parameters.TryGetValue(required, out var value) || value is null)",
		"            {",
		"                unresolved.Add(required);",
		"            }",
		"        }",
		"",
		"        return new Dictionary<string, object?>",
		"        {",
		`            ["selected_binding"] = selectedBinding,`,
		`            ["semantic_input"] = semanticInput,`,
		`            ["adapter_input"] = adapterInput,`,
		`            ["backend_input_contract"] = contract,`,
		`            ["unresolved_required_backend_inputs"] = unresolved,`,
		"        };",
		"    }",
		"",
		"    private static Dictionary<string, object?>? SelectBackendBinding(Dictionary<string, object?> capability)",
		"    {",
		`        var bindings = MapList(capability.GetValueOrDefault("backend_bindings"));`,
		"        return bindings.Count == 0 ? null : bindings[0];",
		"    }",
		"",
		"    private static Dictionary<string, object?> EffectiveBackendInputContract(",
		"        Dictionary<string, object?> capability,",
		"        Dictionary<string, object?>? selectedBinding)",
		"    {",
		`        var mode = FirstNonEmpty(StringValue(selectedBinding, "backend_input_mode"), StringValue(capability, "backend_input_mode"), "implicit")!;`,
		`        var derivedRequired = FirstNonEmptyList(StringList(selectedBinding?.GetValueOrDefault("derived_required_backend_inputs")), StringList(capability.GetValueOrDefault("derived_required_backend_inputs")));`,
		`        var derivedOptional = FirstNonEmptyList(StringList(selectedBinding?.GetValueOrDefault("derived_optional_backend_inputs")), StringList(capability.GetValueOrDefault("derived_optional_backend_inputs")));`,
		`        var explicitRequired = FirstNonEmptyList(StringList(selectedBinding?.GetValueOrDefault("explicit_required_backend_inputs")), StringList(capability.GetValueOrDefault("explicit_required_backend_inputs")));`,
		`        var explicitOptional = FirstNonEmptyList(StringList(selectedBinding?.GetValueOrDefault("explicit_optional_backend_inputs")), StringList(capability.GetValueOrDefault("explicit_optional_backend_inputs")));`,
		"",
		`        if (mode == "explicit")`,
		"        {",
		"            var required = UniqueStrings(explicitRequired);",
		"            return new Dictionary<string, object?>",
		"            {",
		`                ["mode"] = "explicit",`,
		`                ["required"] = required,`,
		`                ["optional"] = Exclude(UniqueStrings(explicitOptional), required),`,
		"            };",
		"        }",
		`        if (mode == "hybrid")`,
		"        {",
		"            var required = UniqueStrings([..derivedRequired, ..explicitRequired]);",
		"            return new Dictionary<string, object?>",
		"            {",
		`                ["mode"] = "hybrid",`,
		`                ["required"] = required,`,
		`                ["optional"] = Exclude(UniqueStrings([..derivedOptional, ..explicitOptional]), required),`,
		"            };",
		"        }",
		"",
		"        var implicitRequired = UniqueStrings(derivedRequired);",
		"        return new Dictionary<string, object?>",
		"        {",
		`            ["mode"] = "implicit",`,
		`            ["required"] = implicitRequired,`,
		`            ["optional"] = Exclude(UniqueStrings(derivedOptional), implicitRequired),`,
		"        };",
		"    }",
		"",
		"    public static List<string> StringList(object? value)",
		"    {",
		"        if (value is List<string> strings) return strings;",
		"        if (value is IEnumerable<object?> objects) return objects.Where(item => item is not null).Select(item => item!.ToString()!).ToList();",
		"        if (value is JsonElement { ValueKind: JsonValueKind.Array } array)",
		"        {",
		"            return array.EnumerateArray().Select(item => item.ValueKind == JsonValueKind.String ? item.GetString() ?? string.Empty : item.ToString()).Where(item => !string.IsNullOrWhiteSpace(item)).ToList();",
		"        }",
		"        return [];",
		"    }",
		"",
		"    private static List<Dictionary<string, object?>> InputList(Dictionary<string, object?> capability, string key)",
		"    {",
		"        return MapList(capability.GetValueOrDefault(key));",
		"    }",
		"",
		"    private static List<Dictionary<string, object?>> MapList(object? value)",
		"    {",
		"        if (value is List<Dictionary<string, object?>> dictionaries) return dictionaries;",
		"        if (value is JsonElement { ValueKind: JsonValueKind.Array } array)",
		"        {",
		"            var result = new List<Dictionary<string, object?>>();",
		"            foreach (var item in array.EnumerateArray())",
		"            {",
		"                if (item.ValueKind != JsonValueKind.Object) continue;",
		"                var map = JsonSerializer.Deserialize<Dictionary<string, object?>>(item.GetRawText());",
		"                if (map is not null) result.Add(map);",
		"            }",
		"            return result;",
		"        }",
		"        return [];",
		"    }",
		"",
		"    private static List<string> GovernanceList(Dictionary<string, object?> capability, string key)",
		"    {",
		`        if (capability.TryGetValue("governance", out var governance) && governance is Dictionary<string, object?> governanceMap)`,
		"        {",
		"            return StringList(governanceMap.GetValueOrDefault(key));",
		"        }",
		`        if (capability.TryGetValue("governance", out governance) && governance is JsonElement { ValueKind: JsonValueKind.Object } governanceElement && governanceElement.TryGetProperty(key, out var property) )`,
		"        {",
		"            return StringList(property);",
		"        }",
		"        return [];",
		"    }",
		"",
		"    private static string StringValue(Dictionary<string, object?>? values, string key)",
		"    {",
		"        if (values is null) return string.Empty;",
		"        return values.TryGetValue(key, out var value) && value is not null ? value.ToString() ?? string.Empty : string.Empty;",
		"    }",
		"",
		"    private static Dictionary<string, object?> DictionaryValue(object? value)",
		"    {",
		"        if (value is Dictionary<string, object?> dictionary) return dictionary;",
		"        if (value is JsonElement { ValueKind: JsonValueKind.Object } element)",
		"        {",
		"            return JsonSerializer.Deserialize<Dictionary<string, object?>>(element.GetRawText()) ?? [];",
		"        }",
		"        return [];",
		"    }",
		"",
		"    private static string? OptionalString(Dictionary<string, object?>? values, string key)",
		"    {",
		"        var value = StringValue(values, key);",
		"        return string.IsNullOrWhiteSpace(value) ? null : value;",
		"    }",
		"",
		"    private static bool BoolValue(object? value)",
		"    {",
		"        if (value is bool flag) return flag;",
		"        if (value is string text && bool.TryParse(text, out var parsed)) return parsed;",
		"        if (value is JsonElement { ValueKind: JsonValueKind.True }) return true;",
		"        if (value is JsonElement { ValueKind: JsonValueKind.False }) return false;",
		"        return false;",
		"    }",
		"",
		"    private static string? FirstNonEmpty(params string?[] values)",
		"    {",
		"        foreach (var value in values)",
		"        {",
		"            if (!string.IsNullOrWhiteSpace(value)) return value;",
		"        }",
		"        return null;",
		"    }",
		"",
		"    private static List<string> FirstNonEmptyList(List<string> primary, List<string> fallback)",
		"    {",
		"        return primary.Count > 0 ? primary : fallback;",
		"    }",
		"",
		"    private static List<string> UniqueStrings(IEnumerable<string> values)",
		"    {",
		"        var result = new List<string>();",
		"        foreach (var value in values)",
		"        {",
		"            if (string.IsNullOrWhiteSpace(value) || result.Contains(value)) continue;",
		"            result.Add(value);",
		"        }",
		"        return result;",
		"    }",
		"",
		"    private static List<string> Exclude(List<string> values, List<string> excluded)",
		"    {",
		"        return values.Where(value => !excluded.Contains(value)).ToList();",
		"    }",
		"",
		"    private static string SideEffectType(string sideEffectLevel)",
		"    {",
		"        var normalized = sideEffectLevel.ToLowerInvariant();",
		`        if (normalized.Contains("irreversible")) return "irreversible";`,
		`        if (normalized.Contains("transaction")) return "transactional";`,
		`        if (normalized.Contains("write")) return "write";`,
		`        return "read";`,
		"    }",
		"",
		"    private static string RollbackWindowFor(string sideEffectLevel)",
		"    {",
		"        return SideEffectType(sideEffectLevel) switch",
		"        {",
		`            "read" => "not_applicable",`,
		`            "irreversible" => "none",`,
		`            _ => "PT15M",`,
		"        };",
		"    }",
		"}",
		"",
	}, "\n")
}

func buildGeneratedCSharpTests(namespaceName string, expectedCapabilityID string) string {
	return strings.Join([]string{
		"using Xunit;",
		"using " + namespaceName + ";",
		"",
		"namespace " + namespaceName + ".Tests;",
		"",
		"public class GeneratedCapabilitiesTests",
		"{",
		"    [Fact]",
		"    public void CreatesCapabilityDefinitions()",
		"    {",
		"        var capabilities = GeneratedCapabilities.CreateAll(BackendAdapter.Default);",
		"        Assert.NotEmpty(capabilities);",
		"        Assert.Equal(" + csharpQuoted(expectedCapabilityID) + ", capabilities.First().Declaration.Name);",
		"    }",
		"}",
		"",
	}, "\n")
}

func csharpProjectName(systemName string) string {
	base := titleCase(strings.NewReplacer("-", " ", "_", " ", ".", " ").Replace(systemName))
	base = strings.ReplaceAll(base, " ", "")
	if base == "" {
		return "GeneratedAnipService"
	}
	return base
}

func csharpNamespace(projectName string) string {
	base := strings.TrimSpace(projectName)
	if base == "" {
		base = "GeneratedAnipService"
	}
	segments := strings.Split(base, ".")
	normalized := make([]string, 0, len(segments))
	for _, segment := range segments {
		var builder strings.Builder
		for index, r := range segment {
			if (r >= 'A' && r <= 'Z') || (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') {
				if index == 0 && r >= '0' && r <= '9' {
					builder.WriteString("Generated")
				}
				builder.WriteRune(r)
			}
		}
		part := builder.String()
		if part != "" {
			normalized = append(normalized, part)
		}
	}
	result := strings.Join(normalized, ".")
	if result == "" {
		return "GeneratedAnipService"
	}
	return result
}

func localCSharpProjectReference(projectRelativePath string) string {
	_, currentFile, _, _ := runtime.Caller(0)
	repoRoot := filepath.Clean(filepath.Join(filepath.Dir(currentFile), "..", "..", ".."))
	return filepath.Join(repoRoot, "packages", "csharp", "src", filepath.FromSlash(projectRelativePath))
}

func csharpQuoted(value string) string {
	return fmt.Sprintf("%q", value)
}
