// ANIP gRPC Transport Binding — canonical service definition.
// All language runtimes generate stubs from this file.
// See: docs/specs/2026-03-23-anip-grpc-transport-design.md

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: anip/v1/anip.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AnipFailure carries structured ANIP protocol failures.
// These are NOT gRPC status errors — they are application-level outcomes.
type AnipFailure struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Type           string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // e.g., "scope_insufficient", "unknown_capability"
	Detail         string                 `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	ResolutionJson string                 `protobuf:"bytes,3,opt,name=resolution_json,json=resolutionJson,proto3" json:"resolution_json,omitempty"` // Optional, JSON string for resolution object
	Retry          bool                   `protobuf:"varint,4,opt,name=retry,proto3" json:"retry,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AnipFailure) Reset() {
	*x = AnipFailure{}
	mi := &file_anip_v1_anip_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnipFailure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnipFailure) ProtoMessage() {}

func (x *AnipFailure) ProtoReflect() protoreflect.Message {
	mi := &file_anip_v1_anip_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnipFailure.ProtoReflect.Descriptor instead.
func (*AnipFailure) Descriptor() ([]byte, []int) {
	return file_anip_v1_anip_proto_rawDescGZIP(), []int{0}
}

func (x *AnipFailure) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AnipFailure) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *AnipFailure) GetResolutionJson() string {
	if x != nil {
		return x.ResolutionJson
	}
	return ""
}

func (x *AnipFailure) GetRetry() bool {
	if x != nil {
		return x.Retry
	}
	return false
}

// Budget represents an enforceable financial budget constraint.
// Carried in delegation token constraints and token issuance requests.
type Budget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Currency      string                 `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`                      // ISO 4217 currency code (e.g., "USD", "EUR")
	MaxAmount     float64                `protobuf:"fixed64,2,opt,name=max_amount,json=maxAmount,proto3" json:"max_amount,omitempty"` // Maximum amount the delegation authorizes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Budget) Reset() {
	*x = Budget{}
	mi := &file_anip_v1_anip_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Budget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Budget) ProtoMessage() {}

func (x *Budget) ProtoReflect() protoreflect.Message {
	mi := &file_anip_v1_anip_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Budget.ProtoReflect.Descriptor instead.
func (*Budget) Descriptor() ([]byte, []int) {
	return file_anip_v1_anip_proto_rawDescGZIP(), []int{1}
}

func (x *Budget) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Budget) GetMaxAmount() float64 {
	if x != nil {
		return x.MaxAmount
	}
	return 0
}

// BudgetContext provides transparency into budget enforcement decisions.
// Present in invoke responses (both success and failure) when a budget was evaluated.
type BudgetContext struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BudgetMax       float64                `protobuf:"fixed64,1,opt,name=budget_max,json=budgetMax,proto3" json:"budget_max,omitempty"`                     // The max_amount from the token's budget constraint
	BudgetCurrency  string                 `protobuf:"bytes,2,opt,name=budget_currency,json=budgetCurrency,proto3" json:"budget_currency,omitempty"`        // The currency from the token's budget constraint
	CostCheckAmount float64                `protobuf:"fixed64,3,opt,name=cost_check_amount,json=costCheckAmount,proto3" json:"cost_check_amount,omitempty"` // The amount used for the pre-execution budget check
	CostCertainty   string                 `protobuf:"bytes,4,opt,name=cost_certainty,json=costCertainty,proto3" json:"cost_certainty,omitempty"`           // The certainty level used (fixed, estimated, dynamic)
	CostActual      float64                `protobuf:"fixed64,5,opt,name=cost_actual,json=costActual,proto3" json:"cost_actual,omitempty"`                  // Actual cost after execution (0 when not yet known)
	WithinBudget    bool                   `protobuf:"varint,6,opt,name=within_budget,json=withinBudget,proto3" json:"within_budget,omitempty"`             // Whether the actual cost was within budget
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BudgetContext) Reset() {
	*x = BudgetContext{}
	mi := &file_anip_v1_anip_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BudgetContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BudgetContext) ProtoMessage() {}

func (x *BudgetContext) ProtoReflect() protoreflect.Message {
	mi := &file_anip_v1_anip_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BudgetContext.ProtoReflect.Descriptor instead.
func (*BudgetContext) Descriptor() ([]byte, []int) {
	return file_anip_v1_anip_proto_rawDescGZIP(), []int{2}
}

func (x *BudgetContext) GetBudgetMax() float64 {
	if x != nil {
		return x.BudgetMax
	}
	return 0
}

func (x *BudgetContext) GetBudgetCurrency() string {
	if x != nil {
		return x.BudgetCurrency
	}
	return ""
}

func (x *BudgetContext) GetCostCheckAmount() float64 {
	if x != nil {
		return x.CostCheckAmount
	}
	return 0
}

func (x *BudgetContext) GetCostCertainty() string {
	if x != nil {
		return x.CostCertainty
	}
	return ""
}

func (x *BudgetContext) GetCostActual() float64 {
	if x != nil {
		return x.CostActual
	}
	return 0
}

func (x *BudgetContext) GetWithinBudget() bool {
	if x != nil {
		return x.WithinBudget
	}
	return false
}

type DiscoveryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoveryRequest) Reset() {
	*x = DiscoveryRequest{}
	mi := &file_anip_v1_anip_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveryRequest) ProtoMessage() {}

func (x *DiscoveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_anip_v1_anip_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveryRequest.ProtoReflect.Descriptor instead.
func (*DiscoveryRequest) Descriptor() ([]byte, []int) {
	return file_anip_v1_anip_proto_rawDescGZIP(), []int{3}
}

type DiscoveryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Json          string                 `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"` // Full discovery document as JSON string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoveryResponse) Reset() {
	*x = DiscoveryResponse{}
	mi := &file_anip_v1_anip_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoveryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveryResponse) ProtoMessage() {}

func (x *DiscoveryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_anip_v1_anip_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveryResponse.ProtoReflect.Descriptor instead.
func (*DiscoveryResponse) Descriptor() ([]byte, []int) {
	return file_anip_v1_anip_proto_rawDescGZIP(), []int{4}
}

func (x *DiscoveryResponse) GetJson() string {
	if x != nil {
		return x.Json
	}
	return ""
}

type ManifestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManifestRequest) Reset() {
	*x = ManifestRequest{}
	mi := &file_anip_v1_anip_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManifestRequest) ProtoMessage() {}

func (x *ManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_anip_v1_anip_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManifestRequest.ProtoReflect.Descriptor instead.
func (*ManifestRequest) Descriptor() ([]byte, []int) {
	return file_anip_v1_anip_proto_rawDescGZIP(), []int{5}
}

type ManifestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ManifestJson  string                 `protobuf:"bytes,1,opt,name=manifest_json,json=manifestJson,proto3" json:"manifest_json,omitempty"` // Full manifest as JSON string
	Signature     string                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`                           // X-ANIP-Signature equivalent
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManifestResponse) Reset() {
	*x = ManifestResponse{}
	mi := &file_anip_v1_anip_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManifestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManifestResponse) ProtoMessage() {}

func (x *ManifestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_anip_v1_anip_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManifestResponse.ProtoReflect.Descriptor instead.
func (*ManifestResponse) Descriptor() ([]byte, []int) {
	return file_anip_v1_anip_proto_rawDescGZIP(), []int{6}
}

func (x *ManifestResponse) GetManifestJson() string {
	if x != nil {
		return x.ManifestJson
	}
	return ""
}

func (x *ManifestResponse) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type JwksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JwksRequest) Reset() {
	*x = JwksRequest{}
	mi := &file_anip_v1_anip_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JwksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JwksRequest) ProtoMessage() {}

func (x *JwksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_anip_v1_anip_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JwksRequest.ProtoReflect.Descriptor instead.
func (*JwksRequest) Descriptor() ([]byte, []int) {
	return file_anip_v1_anip_proto_rawDescGZIP(), []int{7}
}

type JwksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Json          string                 `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"` // Full JWKS document as JSON string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JwksResponse) Reset() {
	*x = JwksResponse{}
	mi := &file_anip_v1_anip_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JwksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JwksResponse) ProtoMessage() {}

func (x *JwksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_anip_v1_anip_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JwksResponse.ProtoReflect.Descriptor instead.
func (*JwksResponse) Descriptor() ([]byte, []int) {
	return file_anip_v1_anip_proto_rawDescGZIP(), []int{8}
}

func (x *JwksResponse) GetJson() string {
	if x != nil {
		return x.Json
	}
	return ""
}

type IssueTokenRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Subject               string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Scope                 []string               `protobuf:"bytes,2,rep,name=scope,proto3" json:"scope,omitempty"`
	Capability            string                 `protobuf:"bytes,3,opt,name=capability,proto3" json:"capability,omitempty"`
	PurposeParametersJson string                 `protobuf:"bytes,4,opt,name=purpose_parameters_json,json=purposeParametersJson,proto3" json:"purpose_parameters_json,omitempty"` // Optional, JSON string
	ParentToken           string                 `protobuf:"bytes,5,opt,name=parent_token,json=parentToken,proto3" json:"parent_token,omitempty"`                                 // Optional, JWT string for sub-delegation
	TtlHours              int32                  `protobuf:"varint,6,opt,name=ttl_hours,json=ttlHours,proto3" json:"ttl_hours,omitempty"`
	CallerClass           string                 `protobuf:"bytes,7,opt,name=caller_class,json=callerClass,proto3" json:"caller_class,omitempty"`
	Budget                *Budget                `protobuf:"bytes,8,opt,name=budget,proto3" json:"budget,omitempty"` // Optional, v0.14: budget constraint to store in token
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *IssueTokenRequest) Reset() {
	*x = IssueTokenRequest{}
	mi := &file_anip_v1_anip_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueTokenRequest) ProtoMessage() {}

func (x *IssueTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_anip_v1_anip_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueTokenRequest.ProtoReflect.Descriptor instead.
func (*IssueTokenRequest) Descriptor() ([]byte, []int) {
	return file_anip_v1_anip_proto_rawDescGZIP(), []int{9}
}

func (x *IssueTokenRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *IssueTokenRequest) GetScope() []string {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *IssueTokenRequest) GetCapability() string {
	if x != nil {
		return x.Capability
	}
	return ""
}

func (x *IssueTokenRequest) GetPurposeParametersJson() string {
	if x != nil {
		return x.PurposeParametersJson
	}
	return ""
}

func (x *IssueTokenRequest) GetParentToken() string {
	if x != nil {
		return x.ParentToken
	}
	return ""
}

func (x *IssueTokenRequest) GetTtlHours() int32 {
	if x != nil {
		return x.TtlHours
	}
	return 0
}

func (x *IssueTokenRequest) GetCallerClass() string {
	if x != nil {
		return x.CallerClass
	}
	return ""
}

func (x *IssueTokenRequest) GetBudget() *Budget {
	if x != nil {
		return x.Budget
	}
	return nil
}

type IssueTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Issued        bool                   `protobuf:"varint,1,opt,name=issued,proto3" json:"issued,omitempty"`
	TokenId       string                 `protobuf:"bytes,2,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`     // JWT string (when issued)
	Expires       string                 `protobuf:"bytes,4,opt,name=expires,proto3" json:"expires,omitempty"` // ISO 8601 (when issued)
	Failure       *AnipFailure           `protobuf:"bytes,5,opt,name=failure,proto3" json:"failure,omitempty"` // When !issued
	Budget        *Budget                `protobuf:"bytes,6,opt,name=budget,proto3" json:"budget,omitempty"`   // v0.14: echoed when budget was requested
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueTokenResponse) Reset() {
	*x = IssueTokenResponse{}
	mi := &file_anip_v1_anip_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueTokenResponse) ProtoMessage() {}

func (x *IssueTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_anip_v1_anip_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueTokenResponse.ProtoReflect.Descriptor instead.
func (*IssueTokenResponse) Descriptor() ([]byte, []int) {
	return file_anip_v1_anip_proto_rawDescGZIP(), []int{10}
}

func (x *IssueTokenResponse) GetIssued() bool {
	if x != nil {
		return x.Issued
	}
	return false
}

func (x *IssueTokenResponse) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *IssueTokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *IssueTokenResponse) GetExpires() string {
	if x != nil {
		return x.Expires
	}
	return ""
}

func (x *IssueTokenResponse) GetFailure() *AnipFailure {
	if x != nil {
		return x.Failure
	}
	return nil
}

func (x *IssueTokenResponse) GetBudget() *Budget {
	if x != nil {
		return x.Budget
	}
	return nil
}

type PermissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionsRequest) Reset() {
	*x = PermissionsRequest{}
	mi := &file_anip_v1_anip_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionsRequest) ProtoMessage() {}

func (x *PermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_anip_v1_anip_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionsRequest.ProtoReflect.Descriptor instead.
func (*PermissionsRequest) Descriptor() ([]byte, []int) {
	return file_anip_v1_anip_proto_rawDescGZIP(), []int{11}
}

type PermissionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Json          string                 `protobuf:"bytes,2,opt,name=json,proto3" json:"json,omitempty"`       // Full permissions response as JSON string (when success)
	Failure       *AnipFailure           `protobuf:"bytes,3,opt,name=failure,proto3" json:"failure,omitempty"` // When !success
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionsResponse) Reset() {
	*x = PermissionsResponse{}
	mi := &file_anip_v1_anip_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionsResponse) ProtoMessage() {}

func (x *PermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_anip_v1_anip_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionsResponse.ProtoReflect.Descriptor instead.
func (*PermissionsResponse) Descriptor() ([]byte, []int) {
	return file_anip_v1_anip_proto_rawDescGZIP(), []int{12}
}

func (x *PermissionsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PermissionsResponse) GetJson() string {
	if x != nil {
		return x.Json
	}
	return ""
}

func (x *PermissionsResponse) GetFailure() *AnipFailure {
	if x != nil {
		return x.Failure
	}
	return nil
}

type InvokeRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Capability         string                 `protobuf:"bytes,1,opt,name=capability,proto3" json:"capability,omitempty"`
	ParametersJson     string                 `protobuf:"bytes,2,opt,name=parameters_json,json=parametersJson,proto3" json:"parameters_json,omitempty"` // JSON string
	ClientReferenceId  string                 `protobuf:"bytes,3,opt,name=client_reference_id,json=clientReferenceId,proto3" json:"client_reference_id,omitempty"`
	TaskId             string                 `protobuf:"bytes,4,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ParentInvocationId string                 `protobuf:"bytes,5,opt,name=parent_invocation_id,json=parentInvocationId,proto3" json:"parent_invocation_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *InvokeRequest) Reset() {
	*x = InvokeRequest{}
	mi := &file_anip_v1_anip_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeRequest) ProtoMessage() {}

func (x *InvokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_anip_v1_anip_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeRequest.ProtoReflect.Descriptor instead.
func (*InvokeRequest) Descriptor() ([]byte, []int) {
	return file_anip_v1_anip_proto_rawDescGZIP(), []int{13}
}

func (x *InvokeRequest) GetCapability() string {
	if x != nil {
		return x.Capability
	}
	return ""
}

func (x *InvokeRequest) GetParametersJson() string {
	if x != nil {
		return x.ParametersJson
	}
	return ""
}

func (x *InvokeRequest) GetClientReferenceId() string {
	if x != nil {
		return x.ClientReferenceId
	}
	return ""
}

func (x *InvokeRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *InvokeRequest) GetParentInvocationId() string {
	if x != nil {
		return x.ParentInvocationId
	}
	return ""
}

type InvokeResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Success            bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	InvocationId       string                 `protobuf:"bytes,2,opt,name=invocation_id,json=invocationId,proto3" json:"invocation_id,omitempty"`
	ClientReferenceId  string                 `protobuf:"bytes,3,opt,name=client_reference_id,json=clientReferenceId,proto3" json:"client_reference_id,omitempty"`
	ResultJson         string                 `protobuf:"bytes,4,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`               // JSON string (when success)
	CostActualJson     string                 `protobuf:"bytes,5,opt,name=cost_actual_json,json=costActualJson,proto3" json:"cost_actual_json,omitempty"` // Optional, JSON string
	Failure            *AnipFailure           `protobuf:"bytes,6,opt,name=failure,proto3" json:"failure,omitempty"`                                       // When !success
	TaskId             string                 `protobuf:"bytes,7,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ParentInvocationId string                 `protobuf:"bytes,8,opt,name=parent_invocation_id,json=parentInvocationId,proto3" json:"parent_invocation_id,omitempty"`
	BudgetContext      *BudgetContext         `protobuf:"bytes,9,opt,name=budget_context,json=budgetContext,proto3" json:"budget_context,omitempty"` // v0.14: present when budget was evaluated
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *InvokeResponse) Reset() {
	*x = InvokeResponse{}
	mi := &file_anip_v1_anip_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeResponse) ProtoMessage() {}

func (x *InvokeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_anip_v1_anip_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeResponse.ProtoReflect.Descriptor instead.
func (*InvokeResponse) Descriptor() ([]byte, []int) {
	return file_anip_v1_anip_proto_rawDescGZIP(), []int{14}
}

func (x *InvokeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InvokeResponse) GetInvocationId() string {
	if x != nil {
		return x.InvocationId
	}
	return ""
}

func (x *InvokeResponse) GetClientReferenceId() string {
	if x != nil {
		return x.ClientReferenceId
	}
	return ""
}

func (x *InvokeResponse) GetResultJson() string {
	if x != nil {
		return x.ResultJson
	}
	return ""
}

func (x *InvokeResponse) GetCostActualJson() string {
	if x != nil {
		return x.CostActualJson
	}
	return ""
}

func (x *InvokeResponse) GetFailure() *AnipFailure {
	if x != nil {
		return x.Failure
	}
	return nil
}

func (x *InvokeResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *InvokeResponse) GetParentInvocationId() string {
	if x != nil {
		return x.ParentInvocationId
	}
	return ""
}

func (x *InvokeResponse) GetBudgetContext() *BudgetContext {
	if x != nil {
		return x.BudgetContext
	}
	return nil
}

type InvokeEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*InvokeEvent_Progress
	//	*InvokeEvent_Completed
	//	*InvokeEvent_Failed
	Event         isInvokeEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeEvent) Reset() {
	*x = InvokeEvent{}
	mi := &file_anip_v1_anip_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeEvent) ProtoMessage() {}

func (x *InvokeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_anip_v1_anip_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeEvent.ProtoReflect.Descriptor instead.
func (*InvokeEvent) Descriptor() ([]byte, []int) {
	return file_anip_v1_anip_proto_rawDescGZIP(), []int{15}
}

func (x *InvokeEvent) GetEvent() isInvokeEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *InvokeEvent) GetProgress() *ProgressEvent {
	if x != nil {
		if x, ok := x.Event.(*InvokeEvent_Progress); ok {
			return x.Progress
		}
	}
	return nil
}

func (x *InvokeEvent) GetCompleted() *CompletedEvent {
	if x != nil {
		if x, ok := x.Event.(*InvokeEvent_Completed); ok {
			return x.Completed
		}
	}
	return nil
}

func (x *InvokeEvent) GetFailed() *FailedEvent {
	if x != nil {
		if x, ok := x.Event.(*InvokeEvent_Failed); ok {
			return x.Failed
		}
	}
	return nil
}

type isInvokeEvent_Event interface {
	isInvokeEvent_Event()
}

type InvokeEvent_Progress struct {
	Progress *ProgressEvent `protobuf:"bytes,1,opt,name=progress,proto3,oneof"`
}

type InvokeEvent_Completed struct {
	Completed *CompletedEvent `protobuf:"bytes,2,opt,name=completed,proto3,oneof"`
}

type InvokeEvent_Failed struct {
	Failed *FailedEvent `protobuf:"bytes,3,opt,name=failed,proto3,oneof"`
}

func (*InvokeEvent_Progress) isInvokeEvent_Event() {}

func (*InvokeEvent_Completed) isInvokeEvent_Event() {}

func (*InvokeEvent_Failed) isInvokeEvent_Event() {}

type ProgressEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InvocationId  string                 `protobuf:"bytes,1,opt,name=invocation_id,json=invocationId,proto3" json:"invocation_id,omitempty"`
	PayloadJson   string                 `protobuf:"bytes,2,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"` // JSON string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgressEvent) Reset() {
	*x = ProgressEvent{}
	mi := &file_anip_v1_anip_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressEvent) ProtoMessage() {}

func (x *ProgressEvent) ProtoReflect() protoreflect.Message {
	mi := &file_anip_v1_anip_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressEvent.ProtoReflect.Descriptor instead.
func (*ProgressEvent) Descriptor() ([]byte, []int) {
	return file_anip_v1_anip_proto_rawDescGZIP(), []int{16}
}

func (x *ProgressEvent) GetInvocationId() string {
	if x != nil {
		return x.InvocationId
	}
	return ""
}

func (x *ProgressEvent) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

type CompletedEvent struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	InvocationId       string                 `protobuf:"bytes,1,opt,name=invocation_id,json=invocationId,proto3" json:"invocation_id,omitempty"`
	ClientReferenceId  string                 `protobuf:"bytes,2,opt,name=client_reference_id,json=clientReferenceId,proto3" json:"client_reference_id,omitempty"`
	ResultJson         string                 `protobuf:"bytes,3,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
	CostActualJson     string                 `protobuf:"bytes,4,opt,name=cost_actual_json,json=costActualJson,proto3" json:"cost_actual_json,omitempty"`
	TaskId             string                 `protobuf:"bytes,5,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ParentInvocationId string                 `protobuf:"bytes,6,opt,name=parent_invocation_id,json=parentInvocationId,proto3" json:"parent_invocation_id,omitempty"`
	BudgetContext      *BudgetContext         `protobuf:"bytes,7,opt,name=budget_context,json=budgetContext,proto3" json:"budget_context,omitempty"` // v0.14: present when budget was evaluated
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CompletedEvent) Reset() {
	*x = CompletedEvent{}
	mi := &file_anip_v1_anip_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompletedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletedEvent) ProtoMessage() {}

func (x *CompletedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_anip_v1_anip_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletedEvent.ProtoReflect.Descriptor instead.
func (*CompletedEvent) Descriptor() ([]byte, []int) {
	return file_anip_v1_anip_proto_rawDescGZIP(), []int{17}
}

func (x *CompletedEvent) GetInvocationId() string {
	if x != nil {
		return x.InvocationId
	}
	return ""
}

func (x *CompletedEvent) GetClientReferenceId() string {
	if x != nil {
		return x.ClientReferenceId
	}
	return ""
}

func (x *CompletedEvent) GetResultJson() string {
	if x != nil {
		return x.ResultJson
	}
	return ""
}

func (x *CompletedEvent) GetCostActualJson() string {
	if x != nil {
		return x.CostActualJson
	}
	return ""
}

func (x *CompletedEvent) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *CompletedEvent) GetParentInvocationId() string {
	if x != nil {
		return x.ParentInvocationId
	}
	return ""
}

func (x *CompletedEvent) GetBudgetContext() *BudgetContext {
	if x != nil {
		return x.BudgetContext
	}
	return nil
}

type FailedEvent struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	InvocationId       string                 `protobuf:"bytes,1,opt,name=invocation_id,json=invocationId,proto3" json:"invocation_id,omitempty"`
	ClientReferenceId  string                 `protobuf:"bytes,2,opt,name=client_reference_id,json=clientReferenceId,proto3" json:"client_reference_id,omitempty"`
	Failure            *AnipFailure           `protobuf:"bytes,3,opt,name=failure,proto3" json:"failure,omitempty"`
	TaskId             string                 `protobuf:"bytes,4,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ParentInvocationId string                 `protobuf:"bytes,5,opt,name=parent_invocation_id,json=parentInvocationId,proto3" json:"parent_invocation_id,omitempty"`
	BudgetContext      *BudgetContext         `protobuf:"bytes,6,opt,name=budget_context,json=budgetContext,proto3" json:"budget_context,omitempty"` // v0.14: present when budget was evaluated
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *FailedEvent) Reset() {
	*x = FailedEvent{}
	mi := &file_anip_v1_anip_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailedEvent) ProtoMessage() {}

func (x *FailedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_anip_v1_anip_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailedEvent.ProtoReflect.Descriptor instead.
func (*FailedEvent) Descriptor() ([]byte, []int) {
	return file_anip_v1_anip_proto_rawDescGZIP(), []int{18}
}

func (x *FailedEvent) GetInvocationId() string {
	if x != nil {
		return x.InvocationId
	}
	return ""
}

func (x *FailedEvent) GetClientReferenceId() string {
	if x != nil {
		return x.ClientReferenceId
	}
	return ""
}

func (x *FailedEvent) GetFailure() *AnipFailure {
	if x != nil {
		return x.Failure
	}
	return nil
}

func (x *FailedEvent) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *FailedEvent) GetParentInvocationId() string {
	if x != nil {
		return x.ParentInvocationId
	}
	return ""
}

func (x *FailedEvent) GetBudgetContext() *BudgetContext {
	if x != nil {
		return x.BudgetContext
	}
	return nil
}

type QueryAuditRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Capability         string                 `protobuf:"bytes,1,opt,name=capability,proto3" json:"capability,omitempty"`
	Since              string                 `protobuf:"bytes,2,opt,name=since,proto3" json:"since,omitempty"`
	InvocationId       string                 `protobuf:"bytes,3,opt,name=invocation_id,json=invocationId,proto3" json:"invocation_id,omitempty"`
	ClientReferenceId  string                 `protobuf:"bytes,4,opt,name=client_reference_id,json=clientReferenceId,proto3" json:"client_reference_id,omitempty"`
	EventClass         string                 `protobuf:"bytes,5,opt,name=event_class,json=eventClass,proto3" json:"event_class,omitempty"`
	Limit              int32                  `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	TaskId             string                 `protobuf:"bytes,7,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ParentInvocationId string                 `protobuf:"bytes,8,opt,name=parent_invocation_id,json=parentInvocationId,proto3" json:"parent_invocation_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *QueryAuditRequest) Reset() {
	*x = QueryAuditRequest{}
	mi := &file_anip_v1_anip_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryAuditRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryAuditRequest) ProtoMessage() {}

func (x *QueryAuditRequest) ProtoReflect() protoreflect.Message {
	mi := &file_anip_v1_anip_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryAuditRequest.ProtoReflect.Descriptor instead.
func (*QueryAuditRequest) Descriptor() ([]byte, []int) {
	return file_anip_v1_anip_proto_rawDescGZIP(), []int{19}
}

func (x *QueryAuditRequest) GetCapability() string {
	if x != nil {
		return x.Capability
	}
	return ""
}

func (x *QueryAuditRequest) GetSince() string {
	if x != nil {
		return x.Since
	}
	return ""
}

func (x *QueryAuditRequest) GetInvocationId() string {
	if x != nil {
		return x.InvocationId
	}
	return ""
}

func (x *QueryAuditRequest) GetClientReferenceId() string {
	if x != nil {
		return x.ClientReferenceId
	}
	return ""
}

func (x *QueryAuditRequest) GetEventClass() string {
	if x != nil {
		return x.EventClass
	}
	return ""
}

func (x *QueryAuditRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *QueryAuditRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *QueryAuditRequest) GetParentInvocationId() string {
	if x != nil {
		return x.ParentInvocationId
	}
	return ""
}

type QueryAuditResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Json          string                 `protobuf:"bytes,2,opt,name=json,proto3" json:"json,omitempty"`       // Full audit response as JSON string (when success)
	Failure       *AnipFailure           `protobuf:"bytes,3,opt,name=failure,proto3" json:"failure,omitempty"` // When !success
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryAuditResponse) Reset() {
	*x = QueryAuditResponse{}
	mi := &file_anip_v1_anip_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryAuditResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryAuditResponse) ProtoMessage() {}

func (x *QueryAuditResponse) ProtoReflect() protoreflect.Message {
	mi := &file_anip_v1_anip_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryAuditResponse.ProtoReflect.Descriptor instead.
func (*QueryAuditResponse) Descriptor() ([]byte, []int) {
	return file_anip_v1_anip_proto_rawDescGZIP(), []int{20}
}

func (x *QueryAuditResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *QueryAuditResponse) GetJson() string {
	if x != nil {
		return x.Json
	}
	return ""
}

func (x *QueryAuditResponse) GetFailure() *AnipFailure {
	if x != nil {
		return x.Failure
	}
	return nil
}

type ListCheckpointsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCheckpointsRequest) Reset() {
	*x = ListCheckpointsRequest{}
	mi := &file_anip_v1_anip_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCheckpointsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCheckpointsRequest) ProtoMessage() {}

func (x *ListCheckpointsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_anip_v1_anip_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCheckpointsRequest.ProtoReflect.Descriptor instead.
func (*ListCheckpointsRequest) Descriptor() ([]byte, []int) {
	return file_anip_v1_anip_proto_rawDescGZIP(), []int{21}
}

func (x *ListCheckpointsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListCheckpointsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Json          string                 `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"` // Full checkpoint list as JSON string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCheckpointsResponse) Reset() {
	*x = ListCheckpointsResponse{}
	mi := &file_anip_v1_anip_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCheckpointsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCheckpointsResponse) ProtoMessage() {}

func (x *ListCheckpointsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_anip_v1_anip_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCheckpointsResponse.ProtoReflect.Descriptor instead.
func (*ListCheckpointsResponse) Descriptor() ([]byte, []int) {
	return file_anip_v1_anip_proto_rawDescGZIP(), []int{22}
}

func (x *ListCheckpointsResponse) GetJson() string {
	if x != nil {
		return x.Json
	}
	return ""
}

type GetCheckpointRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IncludeProof    bool                   `protobuf:"varint,2,opt,name=include_proof,json=includeProof,proto3" json:"include_proof,omitempty"`
	LeafIndex       int32                  `protobuf:"varint,3,opt,name=leaf_index,json=leafIndex,proto3" json:"leaf_index,omitempty"`
	ConsistencyFrom string                 `protobuf:"bytes,4,opt,name=consistency_from,json=consistencyFrom,proto3" json:"consistency_from,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetCheckpointRequest) Reset() {
	*x = GetCheckpointRequest{}
	mi := &file_anip_v1_anip_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCheckpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCheckpointRequest) ProtoMessage() {}

func (x *GetCheckpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_anip_v1_anip_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCheckpointRequest.ProtoReflect.Descriptor instead.
func (*GetCheckpointRequest) Descriptor() ([]byte, []int) {
	return file_anip_v1_anip_proto_rawDescGZIP(), []int{23}
}

func (x *GetCheckpointRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetCheckpointRequest) GetIncludeProof() bool {
	if x != nil {
		return x.IncludeProof
	}
	return false
}

func (x *GetCheckpointRequest) GetLeafIndex() int32 {
	if x != nil {
		return x.LeafIndex
	}
	return 0
}

func (x *GetCheckpointRequest) GetConsistencyFrom() string {
	if x != nil {
		return x.ConsistencyFrom
	}
	return ""
}

type GetCheckpointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Json          string                 `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"` // Full checkpoint detail as JSON string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCheckpointResponse) Reset() {
	*x = GetCheckpointResponse{}
	mi := &file_anip_v1_anip_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCheckpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCheckpointResponse) ProtoMessage() {}

func (x *GetCheckpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_anip_v1_anip_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCheckpointResponse.ProtoReflect.Descriptor instead.
func (*GetCheckpointResponse) Descriptor() ([]byte, []int) {
	return file_anip_v1_anip_proto_rawDescGZIP(), []int{24}
}

func (x *GetCheckpointResponse) GetJson() string {
	if x != nil {
		return x.Json
	}
	return ""
}

var File_anip_v1_anip_proto protoreflect.FileDescriptor

const file_anip_v1_anip_proto_rawDesc = "" +
	"\n" +
	"\x12anip/v1/anip.proto\x12\aanip.v1\"x\n" +
	"\vAnipFailure\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\x12'\n" +
	"\x0fresolution_json\x18\x03 \x01(\tR\x0eresolutionJson\x12\x14\n" +
	"\x05retry\x18\x04 \x01(\bR\x05retry\"C\n" +
	"\x06Budget\x12\x1a\n" +
	"\bcurrency\x18\x01 \x01(\tR\bcurrency\x12\x1d\n" +
	"\n" +
	"max_amount\x18\x02 \x01(\x01R\tmaxAmount\"\xf0\x01\n" +
	"\rBudgetContext\x12\x1d\n" +
	"\n" +
	"budget_max\x18\x01 \x01(\x01R\tbudgetMax\x12'\n" +
	"\x0fbudget_currency\x18\x02 \x01(\tR\x0ebudgetCurrency\x12*\n" +
	"\x11cost_check_amount\x18\x03 \x01(\x01R\x0fcostCheckAmount\x12%\n" +
	"\x0ecost_certainty\x18\x04 \x01(\tR\rcostCertainty\x12\x1f\n" +
	"\vcost_actual\x18\x05 \x01(\x01R\n" +
	"costActual\x12#\n" +
	"\rwithin_budget\x18\x06 \x01(\bR\fwithinBudget\"\x12\n" +
	"\x10DiscoveryRequest\"'\n" +
	"\x11DiscoveryResponse\x12\x12\n" +
	"\x04json\x18\x01 \x01(\tR\x04json\"\x11\n" +
	"\x0fManifestRequest\"U\n" +
	"\x10ManifestResponse\x12#\n" +
	"\rmanifest_json\x18\x01 \x01(\tR\fmanifestJson\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\tR\tsignature\"\r\n" +
	"\vJwksRequest\"\"\n" +
	"\fJwksResponse\x12\x12\n" +
	"\x04json\x18\x01 \x01(\tR\x04json\"\xa7\x02\n" +
	"\x11IssueTokenRequest\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x14\n" +
	"\x05scope\x18\x02 \x03(\tR\x05scope\x12\x1e\n" +
	"\n" +
	"capability\x18\x03 \x01(\tR\n" +
	"capability\x126\n" +
	"\x17purpose_parameters_json\x18\x04 \x01(\tR\x15purposeParametersJson\x12!\n" +
	"\fparent_token\x18\x05 \x01(\tR\vparentToken\x12\x1b\n" +
	"\tttl_hours\x18\x06 \x01(\x05R\bttlHours\x12!\n" +
	"\fcaller_class\x18\a \x01(\tR\vcallerClass\x12'\n" +
	"\x06budget\x18\b \x01(\v2\x0f.anip.v1.BudgetR\x06budget\"\xd0\x01\n" +
	"\x12IssueTokenResponse\x12\x16\n" +
	"\x06issued\x18\x01 \x01(\bR\x06issued\x12\x19\n" +
	"\btoken_id\x18\x02 \x01(\tR\atokenId\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12\x18\n" +
	"\aexpires\x18\x04 \x01(\tR\aexpires\x12.\n" +
	"\afailure\x18\x05 \x01(\v2\x14.anip.v1.AnipFailureR\afailure\x12'\n" +
	"\x06budget\x18\x06 \x01(\v2\x0f.anip.v1.BudgetR\x06budget\"\x14\n" +
	"\x12PermissionsRequest\"s\n" +
	"\x13PermissionsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x12\n" +
	"\x04json\x18\x02 \x01(\tR\x04json\x12.\n" +
	"\afailure\x18\x03 \x01(\v2\x14.anip.v1.AnipFailureR\afailure\"\xd3\x01\n" +
	"\rInvokeRequest\x12\x1e\n" +
	"\n" +
	"capability\x18\x01 \x01(\tR\n" +
	"capability\x12'\n" +
	"\x0fparameters_json\x18\x02 \x01(\tR\x0eparametersJson\x12.\n" +
	"\x13client_reference_id\x18\x03 \x01(\tR\x11clientReferenceId\x12\x17\n" +
	"\atask_id\x18\x04 \x01(\tR\x06taskId\x120\n" +
	"\x14parent_invocation_id\x18\x05 \x01(\tR\x12parentInvocationId\"\x84\x03\n" +
	"\x0eInvokeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rinvocation_id\x18\x02 \x01(\tR\finvocationId\x12.\n" +
	"\x13client_reference_id\x18\x03 \x01(\tR\x11clientReferenceId\x12\x1f\n" +
	"\vresult_json\x18\x04 \x01(\tR\n" +
	"resultJson\x12(\n" +
	"\x10cost_actual_json\x18\x05 \x01(\tR\x0ecostActualJson\x12.\n" +
	"\afailure\x18\x06 \x01(\v2\x14.anip.v1.AnipFailureR\afailure\x12\x17\n" +
	"\atask_id\x18\a \x01(\tR\x06taskId\x120\n" +
	"\x14parent_invocation_id\x18\b \x01(\tR\x12parentInvocationId\x12=\n" +
	"\x0ebudget_context\x18\t \x01(\v2\x16.anip.v1.BudgetContextR\rbudgetContext\"\xb5\x01\n" +
	"\vInvokeEvent\x124\n" +
	"\bprogress\x18\x01 \x01(\v2\x16.anip.v1.ProgressEventH\x00R\bprogress\x127\n" +
	"\tcompleted\x18\x02 \x01(\v2\x17.anip.v1.CompletedEventH\x00R\tcompleted\x12.\n" +
	"\x06failed\x18\x03 \x01(\v2\x14.anip.v1.FailedEventH\x00R\x06failedB\a\n" +
	"\x05event\"W\n" +
	"\rProgressEvent\x12#\n" +
	"\rinvocation_id\x18\x01 \x01(\tR\finvocationId\x12!\n" +
	"\fpayload_json\x18\x02 \x01(\tR\vpayloadJson\"\xba\x02\n" +
	"\x0eCompletedEvent\x12#\n" +
	"\rinvocation_id\x18\x01 \x01(\tR\finvocationId\x12.\n" +
	"\x13client_reference_id\x18\x02 \x01(\tR\x11clientReferenceId\x12\x1f\n" +
	"\vresult_json\x18\x03 \x01(\tR\n" +
	"resultJson\x12(\n" +
	"\x10cost_actual_json\x18\x04 \x01(\tR\x0ecostActualJson\x12\x17\n" +
	"\atask_id\x18\x05 \x01(\tR\x06taskId\x120\n" +
	"\x14parent_invocation_id\x18\x06 \x01(\tR\x12parentInvocationId\x12=\n" +
	"\x0ebudget_context\x18\a \x01(\v2\x16.anip.v1.BudgetContextR\rbudgetContext\"\x9c\x02\n" +
	"\vFailedEvent\x12#\n" +
	"\rinvocation_id\x18\x01 \x01(\tR\finvocationId\x12.\n" +
	"\x13client_reference_id\x18\x02 \x01(\tR\x11clientReferenceId\x12.\n" +
	"\afailure\x18\x03 \x01(\v2\x14.anip.v1.AnipFailureR\afailure\x12\x17\n" +
	"\atask_id\x18\x04 \x01(\tR\x06taskId\x120\n" +
	"\x14parent_invocation_id\x18\x05 \x01(\tR\x12parentInvocationId\x12=\n" +
	"\x0ebudget_context\x18\x06 \x01(\v2\x16.anip.v1.BudgetContextR\rbudgetContext\"\xa0\x02\n" +
	"\x11QueryAuditRequest\x12\x1e\n" +
	"\n" +
	"capability\x18\x01 \x01(\tR\n" +
	"capability\x12\x14\n" +
	"\x05since\x18\x02 \x01(\tR\x05since\x12#\n" +
	"\rinvocation_id\x18\x03 \x01(\tR\finvocationId\x12.\n" +
	"\x13client_reference_id\x18\x04 \x01(\tR\x11clientReferenceId\x12\x1f\n" +
	"\vevent_class\x18\x05 \x01(\tR\n" +
	"eventClass\x12\x14\n" +
	"\x05limit\x18\x06 \x01(\x05R\x05limit\x12\x17\n" +
	"\atask_id\x18\a \x01(\tR\x06taskId\x120\n" +
	"\x14parent_invocation_id\x18\b \x01(\tR\x12parentInvocationId\"r\n" +
	"\x12QueryAuditResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x12\n" +
	"\x04json\x18\x02 \x01(\tR\x04json\x12.\n" +
	"\afailure\x18\x03 \x01(\v2\x14.anip.v1.AnipFailureR\afailure\".\n" +
	"\x16ListCheckpointsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"-\n" +
	"\x17ListCheckpointsResponse\x12\x12\n" +
	"\x04json\x18\x01 \x01(\tR\x04json\"\x95\x01\n" +
	"\x14GetCheckpointRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rinclude_proof\x18\x02 \x01(\bR\fincludeProof\x12\x1d\n" +
	"\n" +
	"leaf_index\x18\x03 \x01(\x05R\tleafIndex\x12)\n" +
	"\x10consistency_from\x18\x04 \x01(\tR\x0fconsistencyFrom\"+\n" +
	"\x15GetCheckpointResponse\x12\x12\n" +
	"\x04json\x18\x01 \x01(\tR\x04json2\xc0\x05\n" +
	"\vAnipService\x12B\n" +
	"\tDiscovery\x12\x19.anip.v1.DiscoveryRequest\x1a\x1a.anip.v1.DiscoveryResponse\x12?\n" +
	"\bManifest\x12\x18.anip.v1.ManifestRequest\x1a\x19.anip.v1.ManifestResponse\x123\n" +
	"\x04Jwks\x12\x14.anip.v1.JwksRequest\x1a\x15.anip.v1.JwksResponse\x12T\n" +
	"\x0fListCheckpoints\x12\x1f.anip.v1.ListCheckpointsRequest\x1a .anip.v1.ListCheckpointsResponse\x12N\n" +
	"\rGetCheckpoint\x12\x1d.anip.v1.GetCheckpointRequest\x1a\x1e.anip.v1.GetCheckpointResponse\x12E\n" +
	"\n" +
	"IssueToken\x12\x1a.anip.v1.IssueTokenRequest\x1a\x1b.anip.v1.IssueTokenResponse\x12H\n" +
	"\vPermissions\x12\x1b.anip.v1.PermissionsRequest\x1a\x1c.anip.v1.PermissionsResponse\x129\n" +
	"\x06Invoke\x12\x16.anip.v1.InvokeRequest\x1a\x17.anip.v1.InvokeResponse\x12>\n" +
	"\fInvokeStream\x12\x16.anip.v1.InvokeRequest\x1a\x14.anip.v1.InvokeEvent0\x01\x12E\n" +
	"\n" +
	"QueryAudit\x12\x1a.anip.v1.QueryAuditRequest\x1a\x1b.anip.v1.QueryAuditResponseBAZ?github.com/anip-protocol/anip/packages/go/grpcapi/proto/anip/v1b\x06proto3"

var (
	file_anip_v1_anip_proto_rawDescOnce sync.Once
	file_anip_v1_anip_proto_rawDescData []byte
)

func file_anip_v1_anip_proto_rawDescGZIP() []byte {
	file_anip_v1_anip_proto_rawDescOnce.Do(func() {
		file_anip_v1_anip_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_anip_v1_anip_proto_rawDesc), len(file_anip_v1_anip_proto_rawDesc)))
	})
	return file_anip_v1_anip_proto_rawDescData
}

var file_anip_v1_anip_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_anip_v1_anip_proto_goTypes = []any{
	(*AnipFailure)(nil),             // 0: anip.v1.AnipFailure
	(*Budget)(nil),                  // 1: anip.v1.Budget
	(*BudgetContext)(nil),           // 2: anip.v1.BudgetContext
	(*DiscoveryRequest)(nil),        // 3: anip.v1.DiscoveryRequest
	(*DiscoveryResponse)(nil),       // 4: anip.v1.DiscoveryResponse
	(*ManifestRequest)(nil),         // 5: anip.v1.ManifestRequest
	(*ManifestResponse)(nil),        // 6: anip.v1.ManifestResponse
	(*JwksRequest)(nil),             // 7: anip.v1.JwksRequest
	(*JwksResponse)(nil),            // 8: anip.v1.JwksResponse
	(*IssueTokenRequest)(nil),       // 9: anip.v1.IssueTokenRequest
	(*IssueTokenResponse)(nil),      // 10: anip.v1.IssueTokenResponse
	(*PermissionsRequest)(nil),      // 11: anip.v1.PermissionsRequest
	(*PermissionsResponse)(nil),     // 12: anip.v1.PermissionsResponse
	(*InvokeRequest)(nil),           // 13: anip.v1.InvokeRequest
	(*InvokeResponse)(nil),          // 14: anip.v1.InvokeResponse
	(*InvokeEvent)(nil),             // 15: anip.v1.InvokeEvent
	(*ProgressEvent)(nil),           // 16: anip.v1.ProgressEvent
	(*CompletedEvent)(nil),          // 17: anip.v1.CompletedEvent
	(*FailedEvent)(nil),             // 18: anip.v1.FailedEvent
	(*QueryAuditRequest)(nil),       // 19: anip.v1.QueryAuditRequest
	(*QueryAuditResponse)(nil),      // 20: anip.v1.QueryAuditResponse
	(*ListCheckpointsRequest)(nil),  // 21: anip.v1.ListCheckpointsRequest
	(*ListCheckpointsResponse)(nil), // 22: anip.v1.ListCheckpointsResponse
	(*GetCheckpointRequest)(nil),    // 23: anip.v1.GetCheckpointRequest
	(*GetCheckpointResponse)(nil),   // 24: anip.v1.GetCheckpointResponse
}
var file_anip_v1_anip_proto_depIdxs = []int32{
	1,  // 0: anip.v1.IssueTokenRequest.budget:type_name -> anip.v1.Budget
	0,  // 1: anip.v1.IssueTokenResponse.failure:type_name -> anip.v1.AnipFailure
	1,  // 2: anip.v1.IssueTokenResponse.budget:type_name -> anip.v1.Budget
	0,  // 3: anip.v1.PermissionsResponse.failure:type_name -> anip.v1.AnipFailure
	0,  // 4: anip.v1.InvokeResponse.failure:type_name -> anip.v1.AnipFailure
	2,  // 5: anip.v1.InvokeResponse.budget_context:type_name -> anip.v1.BudgetContext
	16, // 6: anip.v1.InvokeEvent.progress:type_name -> anip.v1.ProgressEvent
	17, // 7: anip.v1.InvokeEvent.completed:type_name -> anip.v1.CompletedEvent
	18, // 8: anip.v1.InvokeEvent.failed:type_name -> anip.v1.FailedEvent
	2,  // 9: anip.v1.CompletedEvent.budget_context:type_name -> anip.v1.BudgetContext
	0,  // 10: anip.v1.FailedEvent.failure:type_name -> anip.v1.AnipFailure
	2,  // 11: anip.v1.FailedEvent.budget_context:type_name -> anip.v1.BudgetContext
	0,  // 12: anip.v1.QueryAuditResponse.failure:type_name -> anip.v1.AnipFailure
	3,  // 13: anip.v1.AnipService.Discovery:input_type -> anip.v1.DiscoveryRequest
	5,  // 14: anip.v1.AnipService.Manifest:input_type -> anip.v1.ManifestRequest
	7,  // 15: anip.v1.AnipService.Jwks:input_type -> anip.v1.JwksRequest
	21, // 16: anip.v1.AnipService.ListCheckpoints:input_type -> anip.v1.ListCheckpointsRequest
	23, // 17: anip.v1.AnipService.GetCheckpoint:input_type -> anip.v1.GetCheckpointRequest
	9,  // 18: anip.v1.AnipService.IssueToken:input_type -> anip.v1.IssueTokenRequest
	11, // 19: anip.v1.AnipService.Permissions:input_type -> anip.v1.PermissionsRequest
	13, // 20: anip.v1.AnipService.Invoke:input_type -> anip.v1.InvokeRequest
	13, // 21: anip.v1.AnipService.InvokeStream:input_type -> anip.v1.InvokeRequest
	19, // 22: anip.v1.AnipService.QueryAudit:input_type -> anip.v1.QueryAuditRequest
	4,  // 23: anip.v1.AnipService.Discovery:output_type -> anip.v1.DiscoveryResponse
	6,  // 24: anip.v1.AnipService.Manifest:output_type -> anip.v1.ManifestResponse
	8,  // 25: anip.v1.AnipService.Jwks:output_type -> anip.v1.JwksResponse
	22, // 26: anip.v1.AnipService.ListCheckpoints:output_type -> anip.v1.ListCheckpointsResponse
	24, // 27: anip.v1.AnipService.GetCheckpoint:output_type -> anip.v1.GetCheckpointResponse
	10, // 28: anip.v1.AnipService.IssueToken:output_type -> anip.v1.IssueTokenResponse
	12, // 29: anip.v1.AnipService.Permissions:output_type -> anip.v1.PermissionsResponse
	14, // 30: anip.v1.AnipService.Invoke:output_type -> anip.v1.InvokeResponse
	15, // 31: anip.v1.AnipService.InvokeStream:output_type -> anip.v1.InvokeEvent
	20, // 32: anip.v1.AnipService.QueryAudit:output_type -> anip.v1.QueryAuditResponse
	23, // [23:33] is the sub-list for method output_type
	13, // [13:23] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_anip_v1_anip_proto_init() }
func file_anip_v1_anip_proto_init() {
	if File_anip_v1_anip_proto != nil {
		return
	}
	file_anip_v1_anip_proto_msgTypes[15].OneofWrappers = []any{
		(*InvokeEvent_Progress)(nil),
		(*InvokeEvent_Completed)(nil),
		(*InvokeEvent_Failed)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_anip_v1_anip_proto_rawDesc), len(file_anip_v1_anip_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_anip_v1_anip_proto_goTypes,
		DependencyIndexes: file_anip_v1_anip_proto_depIdxs,
		MessageInfos:      file_anip_v1_anip_proto_msgTypes,
	}.Build()
	File_anip_v1_anip_proto = out.File
	file_anip_v1_anip_proto_goTypes = nil
	file_anip_v1_anip_proto_depIdxs = nil
}
