// ANIP gRPC Transport Binding — canonical service definition.
// All language runtimes generate stubs from this file.
// See: docs/specs/2026-03-23-anip-grpc-transport-design.md

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/anip/v1/anip.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AnipService_Discovery_FullMethodName       = "/anip.v1.AnipService/Discovery"
	AnipService_Manifest_FullMethodName        = "/anip.v1.AnipService/Manifest"
	AnipService_Jwks_FullMethodName            = "/anip.v1.AnipService/Jwks"
	AnipService_ListCheckpoints_FullMethodName = "/anip.v1.AnipService/ListCheckpoints"
	AnipService_GetCheckpoint_FullMethodName   = "/anip.v1.AnipService/GetCheckpoint"
	AnipService_IssueToken_FullMethodName      = "/anip.v1.AnipService/IssueToken"
	AnipService_Permissions_FullMethodName     = "/anip.v1.AnipService/Permissions"
	AnipService_Invoke_FullMethodName          = "/anip.v1.AnipService/Invoke"
	AnipService_InvokeStream_FullMethodName    = "/anip.v1.AnipService/InvokeStream"
	AnipService_QueryAudit_FullMethodName      = "/anip.v1.AnipService/QueryAudit"
)

// AnipServiceClient is the client API for AnipService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AnipService exposes the full ANIP protocol over gRPC.
// Auth: bearer token via "authorization" call metadata.
type AnipServiceClient interface {
	// --- Public (no auth) ---
	Discovery(ctx context.Context, in *DiscoveryRequest, opts ...grpc.CallOption) (*DiscoveryResponse, error)
	Manifest(ctx context.Context, in *ManifestRequest, opts ...grpc.CallOption) (*ManifestResponse, error)
	Jwks(ctx context.Context, in *JwksRequest, opts ...grpc.CallOption) (*JwksResponse, error)
	ListCheckpoints(ctx context.Context, in *ListCheckpointsRequest, opts ...grpc.CallOption) (*ListCheckpointsResponse, error)
	GetCheckpoint(ctx context.Context, in *GetCheckpointRequest, opts ...grpc.CallOption) (*GetCheckpointResponse, error)
	// --- Bootstrap or JWT auth ---
	IssueToken(ctx context.Context, in *IssueTokenRequest, opts ...grpc.CallOption) (*IssueTokenResponse, error)
	// --- JWT auth ---
	Permissions(ctx context.Context, in *PermissionsRequest, opts ...grpc.CallOption) (*PermissionsResponse, error)
	Invoke(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (*InvokeResponse, error)
	InvokeStream(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[InvokeEvent], error)
	QueryAudit(ctx context.Context, in *QueryAuditRequest, opts ...grpc.CallOption) (*QueryAuditResponse, error)
}

type anipServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAnipServiceClient(cc grpc.ClientConnInterface) AnipServiceClient {
	return &anipServiceClient{cc}
}

func (c *anipServiceClient) Discovery(ctx context.Context, in *DiscoveryRequest, opts ...grpc.CallOption) (*DiscoveryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiscoveryResponse)
	err := c.cc.Invoke(ctx, AnipService_Discovery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *anipServiceClient) Manifest(ctx context.Context, in *ManifestRequest, opts ...grpc.CallOption) (*ManifestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ManifestResponse)
	err := c.cc.Invoke(ctx, AnipService_Manifest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *anipServiceClient) Jwks(ctx context.Context, in *JwksRequest, opts ...grpc.CallOption) (*JwksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JwksResponse)
	err := c.cc.Invoke(ctx, AnipService_Jwks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *anipServiceClient) ListCheckpoints(ctx context.Context, in *ListCheckpointsRequest, opts ...grpc.CallOption) (*ListCheckpointsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCheckpointsResponse)
	err := c.cc.Invoke(ctx, AnipService_ListCheckpoints_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *anipServiceClient) GetCheckpoint(ctx context.Context, in *GetCheckpointRequest, opts ...grpc.CallOption) (*GetCheckpointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCheckpointResponse)
	err := c.cc.Invoke(ctx, AnipService_GetCheckpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *anipServiceClient) IssueToken(ctx context.Context, in *IssueTokenRequest, opts ...grpc.CallOption) (*IssueTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IssueTokenResponse)
	err := c.cc.Invoke(ctx, AnipService_IssueToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *anipServiceClient) Permissions(ctx context.Context, in *PermissionsRequest, opts ...grpc.CallOption) (*PermissionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PermissionsResponse)
	err := c.cc.Invoke(ctx, AnipService_Permissions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *anipServiceClient) Invoke(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (*InvokeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InvokeResponse)
	err := c.cc.Invoke(ctx, AnipService_Invoke_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *anipServiceClient) InvokeStream(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[InvokeEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AnipService_ServiceDesc.Streams[0], AnipService_InvokeStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[InvokeRequest, InvokeEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AnipService_InvokeStreamClient = grpc.ServerStreamingClient[InvokeEvent]

func (c *anipServiceClient) QueryAudit(ctx context.Context, in *QueryAuditRequest, opts ...grpc.CallOption) (*QueryAuditResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryAuditResponse)
	err := c.cc.Invoke(ctx, AnipService_QueryAudit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnipServiceServer is the server API for AnipService service.
// All implementations must embed UnimplementedAnipServiceServer
// for forward compatibility.
//
// AnipService exposes the full ANIP protocol over gRPC.
// Auth: bearer token via "authorization" call metadata.
type AnipServiceServer interface {
	// --- Public (no auth) ---
	Discovery(context.Context, *DiscoveryRequest) (*DiscoveryResponse, error)
	Manifest(context.Context, *ManifestRequest) (*ManifestResponse, error)
	Jwks(context.Context, *JwksRequest) (*JwksResponse, error)
	ListCheckpoints(context.Context, *ListCheckpointsRequest) (*ListCheckpointsResponse, error)
	GetCheckpoint(context.Context, *GetCheckpointRequest) (*GetCheckpointResponse, error)
	// --- Bootstrap or JWT auth ---
	IssueToken(context.Context, *IssueTokenRequest) (*IssueTokenResponse, error)
	// --- JWT auth ---
	Permissions(context.Context, *PermissionsRequest) (*PermissionsResponse, error)
	Invoke(context.Context, *InvokeRequest) (*InvokeResponse, error)
	InvokeStream(*InvokeRequest, grpc.ServerStreamingServer[InvokeEvent]) error
	QueryAudit(context.Context, *QueryAuditRequest) (*QueryAuditResponse, error)
	mustEmbedUnimplementedAnipServiceServer()
}

// UnimplementedAnipServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAnipServiceServer struct{}

func (UnimplementedAnipServiceServer) Discovery(context.Context, *DiscoveryRequest) (*DiscoveryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Discovery not implemented")
}
func (UnimplementedAnipServiceServer) Manifest(context.Context, *ManifestRequest) (*ManifestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Manifest not implemented")
}
func (UnimplementedAnipServiceServer) Jwks(context.Context, *JwksRequest) (*JwksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Jwks not implemented")
}
func (UnimplementedAnipServiceServer) ListCheckpoints(context.Context, *ListCheckpointsRequest) (*ListCheckpointsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCheckpoints not implemented")
}
func (UnimplementedAnipServiceServer) GetCheckpoint(context.Context, *GetCheckpointRequest) (*GetCheckpointResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCheckpoint not implemented")
}
func (UnimplementedAnipServiceServer) IssueToken(context.Context, *IssueTokenRequest) (*IssueTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IssueToken not implemented")
}
func (UnimplementedAnipServiceServer) Permissions(context.Context, *PermissionsRequest) (*PermissionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Permissions not implemented")
}
func (UnimplementedAnipServiceServer) Invoke(context.Context, *InvokeRequest) (*InvokeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Invoke not implemented")
}
func (UnimplementedAnipServiceServer) InvokeStream(*InvokeRequest, grpc.ServerStreamingServer[InvokeEvent]) error {
	return status.Error(codes.Unimplemented, "method InvokeStream not implemented")
}
func (UnimplementedAnipServiceServer) QueryAudit(context.Context, *QueryAuditRequest) (*QueryAuditResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryAudit not implemented")
}
func (UnimplementedAnipServiceServer) mustEmbedUnimplementedAnipServiceServer() {}
func (UnimplementedAnipServiceServer) testEmbeddedByValue()                     {}

// UnsafeAnipServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnipServiceServer will
// result in compilation errors.
type UnsafeAnipServiceServer interface {
	mustEmbedUnimplementedAnipServiceServer()
}

func RegisterAnipServiceServer(s grpc.ServiceRegistrar, srv AnipServiceServer) {
	// If the following call panics, it indicates UnimplementedAnipServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AnipService_ServiceDesc, srv)
}

func _AnipService_Discovery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscoveryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnipServiceServer).Discovery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnipService_Discovery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnipServiceServer).Discovery(ctx, req.(*DiscoveryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnipService_Manifest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ManifestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnipServiceServer).Manifest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnipService_Manifest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnipServiceServer).Manifest(ctx, req.(*ManifestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnipService_Jwks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JwksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnipServiceServer).Jwks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnipService_Jwks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnipServiceServer).Jwks(ctx, req.(*JwksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnipService_ListCheckpoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCheckpointsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnipServiceServer).ListCheckpoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnipService_ListCheckpoints_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnipServiceServer).ListCheckpoints(ctx, req.(*ListCheckpointsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnipService_GetCheckpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCheckpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnipServiceServer).GetCheckpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnipService_GetCheckpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnipServiceServer).GetCheckpoint(ctx, req.(*GetCheckpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnipService_IssueToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IssueTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnipServiceServer).IssueToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnipService_IssueToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnipServiceServer).IssueToken(ctx, req.(*IssueTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnipService_Permissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PermissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnipServiceServer).Permissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnipService_Permissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnipServiceServer).Permissions(ctx, req.(*PermissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnipService_Invoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvokeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnipServiceServer).Invoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnipService_Invoke_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnipServiceServer).Invoke(ctx, req.(*InvokeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnipService_InvokeStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(InvokeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AnipServiceServer).InvokeStream(m, &grpc.GenericServerStream[InvokeRequest, InvokeEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AnipService_InvokeStreamServer = grpc.ServerStreamingServer[InvokeEvent]

func _AnipService_QueryAudit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAuditRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnipServiceServer).QueryAudit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnipService_QueryAudit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnipServiceServer).QueryAudit(ctx, req.(*QueryAuditRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AnipService_ServiceDesc is the grpc.ServiceDesc for AnipService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AnipService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "anip.v1.AnipService",
	HandlerType: (*AnipServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Discovery",
			Handler:    _AnipService_Discovery_Handler,
		},
		{
			MethodName: "Manifest",
			Handler:    _AnipService_Manifest_Handler,
		},
		{
			MethodName: "Jwks",
			Handler:    _AnipService_Jwks_Handler,
		},
		{
			MethodName: "ListCheckpoints",
			Handler:    _AnipService_ListCheckpoints_Handler,
		},
		{
			MethodName: "GetCheckpoint",
			Handler:    _AnipService_GetCheckpoint_Handler,
		},
		{
			MethodName: "IssueToken",
			Handler:    _AnipService_IssueToken_Handler,
		},
		{
			MethodName: "Permissions",
			Handler:    _AnipService_Permissions_Handler,
		},
		{
			MethodName: "Invoke",
			Handler:    _AnipService_Invoke_Handler,
		},
		{
			MethodName: "QueryAudit",
			Handler:    _AnipService_QueryAudit_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "InvokeStream",
			Handler:       _AnipService_InvokeStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/anip/v1/anip.proto",
}
