// AUTO-GENERATED by scripts/build-design-packs.ts — do not edit by hand

import type { DesignPack } from '../types'

export const PACKS: DesignPack[] = [
  {
    "meta": {
      "id": "deploy-verify-multiservice",
      "name": "deploy-verify-estate",
      "domain": "devops",
      "category": "orchestration",
      "narrative": "An agent deploys a service through one ANIP surface and must verify rollout health through a separate monitoring service. The interface should expose enough relationship clarity that the post-deplo...",
      "result": null,
      "isMultiService": true
    },
    "requirements": {
      "system": {
        "name": "deploy-verify-estate",
        "domain": "devops",
        "deployment_intent": "multi_service_agent_execution"
      },
      "services": [
        {
          "name": "deploy-service",
          "role": "execution",
          "public_http": true
        },
        {
          "name": "monitoring-service",
          "role": "verification",
          "public_http": true
        }
      ],
      "transports": {
        "http": true,
        "stdio": false,
        "grpc": false
      },
      "trust": {
        "mode": "signed",
        "checkpoints": false
      },
      "auth": {
        "delegation_tokens": true,
        "purpose_binding": true,
        "scoped_authority": true,
        "service_to_service_handoffs": true
      },
      "permissions": {
        "preflight_discovery": true,
        "restricted_vs_denied": true
      },
      "audit": {
        "durable": true,
        "searchable": true,
        "cross_service_reconstruction_required": true
      },
      "lineage": {
        "invocation_id": true,
        "client_reference_id": true,
        "task_id": true,
        "parent_invocation_id": true,
        "cross_service_continuity_required": true
      },
      "risk_profile": {
        "execution_service": {
          "deploy_service": {
            "side_effect": "irreversible",
            "recovery_guidance_required": true
          }
        },
        "verification_service": {
          "get_deployment_status": {
            "side_effect": "none"
          }
        }
      },
      "business_constraints": {
        "cross_service_verification_should_not_depend_on_operator_memory": true,
        "deploy_to_monitoring_relationship_should_be_machine_visible": true,
        "execution_and_verification_capabilities_live_in_different_services": true
      },
      "scale": {
        "shape_preference": "multi_service_estate",
        "high_availability": false
      }
    },
    "proposal": {
      "proposal": {
        "recommended_shape": "multi_service_estate",
        "rationale": [
          "deployment and verification are intentionally split across services",
          "continuity is necessary but not sufficient",
          "the main gap is distributed verification-path discoverability"
        ],
        "service_shapes": {
          "deploy-service": {
            "shape": "production_single_service"
          },
          "monitoring-service": {
            "shape": "production_single_service"
          }
        },
        "shared_requirements": [
          "cross-service continuity",
          "durable audit in both services",
          "discoverable verification relationship across services"
        ],
        "required_components": [
          "manifest_generator_per_service",
          "token_verifier_per_service",
          "invocation_executor_per_service",
          "durable_audit_store_per_service",
          "lineage_recorder_per_service",
          "bounded_cross_service_verification_guidance"
        ],
        "anti_pattern_warnings": [
          "do_not_force_agents_to_guess_the_monitoring_service_after_deploy",
          "do_not_push_verification_routes_only_into_human_runbooks"
        ],
        "expected_glue_reduction": {
          "orchestration": [
            "deploy_then_verify_service_map_glue",
            "cross_service_post_action_check_guesswork"
          ]
        }
      }
    },
    "scenario": {
      "scenario": {
        "name": "deploy_on_one_service_verify_on_another",
        "category": "orchestration",
        "narrative": "An agent deploys a service through one ANIP surface and must verify rollout health through a separate monitoring service. The interface should expose enough relationship clarity that the post-deploy verification path does not depend on wrapper-side service maps.\n",
        "context": {
          "execution_service_capability": "deploy_service",
          "verification_service_capability": "get_deployment_status",
          "side_effect_execution": "transactional",
          "task_id": "deploy-cross-service-2026-04",
          "parent_deploy_invocation_id": "inv-deploy-xsvc-001",
          "token_scope_service_a": [
            "deploy:write"
          ],
          "token_scope_service_b": [
            "deploy:read"
          ]
        },
        "expected_behavior": [
          "deployment_service_preserves_lineage",
          "verification_service_link_is_discoverable",
          "operator_can_reconstruct_deploy_then_verify_chain"
        ],
        "expected_anip_support": [
          "task_id_support",
          "parent_invocation_id_support",
          "audit_queryability",
          "cross_service_verification_guidance"
        ]
      }
    },
    "evaluation": null
  },
  {
    "meta": {
      "id": "devops-single",
      "name": "devops-operations-service",
      "domain": "devops",
      "category": "safety",
      "narrative": "An agent is operating on behalf of an engineer. The engineer can inspect clusters but does not hold authority to delete a production cluster. The agent is asked to delete cluster prod-eu-1.",
      "result": "HANDLED",
      "isMultiService": false
    },
    "requirements": {
      "system": {
        "name": "devops-operations-service",
        "domain": "devops",
        "deployment_intent": "internal_control_surface"
      },
      "transports": {
        "http": true,
        "stdio": false,
        "grpc": false
      },
      "trust": {
        "mode": "signed",
        "checkpoints": false
      },
      "auth": {
        "delegation_tokens": true,
        "purpose_binding": true,
        "scoped_authority": true
      },
      "permissions": {
        "preflight_discovery": true,
        "restricted_vs_denied": true,
        "grantable_requirements": true
      },
      "audit": {
        "durable": true,
        "searchable": true
      },
      "lineage": {
        "invocation_id": true,
        "client_reference_id": true,
        "task_id": true,
        "parent_invocation_id": true
      },
      "risk_profile": {
        "capabilities": {
          "list_clusters": {
            "side_effect": "none"
          },
          "delete_cluster": {
            "side_effect": "irreversible",
            "high_risk": true,
            "recovery_guidance_required": true
          }
        }
      },
      "business_constraints": {
        "production_cluster_deletion_requires_strong_authority": true,
        "blocked_high_risk_actions_should_escalate_cleanly": true,
        "repeated_blind_retry_is_unacceptable": true
      },
      "scale": {
        "shape_preference": "production_single_service",
        "high_availability": false
      }
    },
    "proposal": {
      "proposal": {
        "recommended_shape": "production_single_service",
        "rationale": [
          "internal HTTP control surface is sufficient",
          "durable audit and lineage are required",
          "permission discovery is critical before destructive actions",
          "no separate worker split is necessary yet"
        ],
        "required_components": [
          "capability_registry",
          "manifest_generator",
          "token_verifier",
          "delegation_engine",
          "permission_evaluator",
          "invocation_executor",
          "failure_mapper",
          "durable_audit_store",
          "lineage_recorder",
          "http_adapter"
        ],
        "optional_components": [
          "token_issuer",
          "checkpoint_worker",
          "embedded_studio"
        ],
        "key_runtime_requirements": [
          "expose high-risk irreversible posture for delete_cluster",
          "support permission discovery before invocation",
          "distinguish restricted vs denied",
          "preserve task and invocation lineage",
          "return structured failure with escalation-friendly recovery data"
        ],
        "anti_pattern_warnings": [
          "do_not_rely_on_delete_then_parse_error",
          "do_not_hide_authority_requirements_only_in_docs",
          "do_not_push_lineage_only_into_logs"
        ],
        "expected_glue_reduction": {
          "safety": [
            "destructive_action_wrapper_glue",
            "blind_retry_glue"
          ],
          "orchestration": [
            "ad_hoc_escalation_branches"
          ],
          "observability": [
            "incident_trace_stitching",
            "action_chain_reconstruction"
          ]
        }
      }
    },
    "scenario": {
      "scenario": {
        "name": "delete_production_cluster_without_permission",
        "category": "safety",
        "narrative": "An agent is operating on behalf of an engineer. The engineer can inspect clusters but does not hold authority to delete a production cluster. The agent is asked to delete cluster prod-eu-1.\n",
        "context": {
          "capability": "delete_cluster",
          "target": "prod-eu-1",
          "side_effect": "irreversible",
          "risk": "high",
          "token_scope": [
            "clusters:read"
          ],
          "permissions_state": "denied",
          "task_id": "incident-cleanup-2026-03",
          "client_reference_id": "step-7-delete",
          "parent_invocation_id": "inv-a1b2c3d4e5f6"
        },
        "expected_behavior": [
          "do_not_execute",
          "do_not_retry_blindly",
          "explain_authority_gap",
          "preserve_task_identity",
          "preserve_parent_invocation_lineage",
          "produce_audit_entry",
          "suggest_escalation_or_human_hand_off"
        ],
        "expected_anip_support": [
          "permission_discovery",
          "irreversible_side_effect_visibility",
          "structured_failure",
          "resolution_guidance",
          "task_id_support",
          "parent_invocation_id_support",
          "audit_queryability"
        ]
      }
    },
    "evaluation": {
      "evaluation": {
        "scenario_name": "delete_production_cluster_without_permission",
        "result": "HANDLED",
        "handled_by_anip": [
          "permission discovery",
          "high-risk side-effect visibility",
          "structured blocked-action failure",
          "escalation-friendly recovery guidance",
          "task identity",
          "parent invocation lineage",
          "durable audit"
        ],
        "glue_you_will_still_write": [
          "you may still write organization-specific approval workflow integration here"
        ],
        "glue_category": [
          "orchestration"
        ],
        "why": [
          "the core scenario requires safe refusal rather than successful execution",
          "the design already exposes enough authority, risk, recovery, and audit context to refuse cleanly",
          "remaining organization-specific approval integration is peripheral to the core scenario behavior"
        ],
        "what_would_improve": [
          "add approval-aware declarations",
          "strengthen escalation vocabulary",
          "integrate more tightly with external approval systems"
        ],
        "confidence": "high"
      }
    }
  },
  {
    "meta": {
      "id": "devops-verify-single",
      "name": "deployment-operations-service",
      "domain": "devops",
      "category": "orchestration",
      "narrative": "An agent deploys a service successfully. The next sensible move is usually to verify rollout status using a separate read capability. The interface should make that relationship visible so the agen...",
      "result": null,
      "isMultiService": false
    },
    "requirements": {
      "system": {
        "name": "deployment-operations-service",
        "domain": "devops",
        "deployment_intent": "internal_control_surface"
      },
      "transports": {
        "http": true,
        "stdio": false,
        "grpc": false
      },
      "trust": {
        "mode": "signed",
        "checkpoints": false
      },
      "auth": {
        "delegation_tokens": true,
        "purpose_binding": true,
        "scoped_authority": true
      },
      "permissions": {
        "preflight_discovery": true,
        "restricted_vs_denied": true
      },
      "audit": {
        "durable": true,
        "searchable": true
      },
      "lineage": {
        "invocation_id": true,
        "client_reference_id": true,
        "task_id": true,
        "parent_invocation_id": true
      },
      "risk_profile": {
        "capabilities": {
          "deploy_service": {
            "side_effect": "reversible",
            "recovery_guidance_required": true
          },
          "get_deployment_status": {
            "side_effect": "none"
          }
        }
      },
      "business_constraints": {
        "writes_should_have_a_discoverable_verification_path": true,
        "operators_should_not_have_to_guess_the_post_action_check": true
      },
      "scale": {
        "shape_preference": "production_single_service",
        "high_availability": false
      }
    },
    "proposal": {
      "proposal": {
        "recommended_shape": "production_single_service",
        "rationale": [
          "deploy and status-check can live in one control surface",
          "the main gap is post-action verification guidance",
          "durable audit and lineage remain required"
        ],
        "required_components": [
          "capability_registry",
          "manifest_generator",
          "token_verifier",
          "delegation_engine",
          "permission_evaluator",
          "invocation_executor",
          "failure_mapper",
          "durable_audit_store",
          "lineage_recorder",
          "http_adapter"
        ],
        "optional_components": [
          "token_issuer",
          "embedded_studio"
        ],
        "key_runtime_requirements": [
          "expose a likely verification capability after deployment",
          "preserve lineage across write and verification steps",
          "keep verification guidance advisory rather than mandatory workflow"
        ],
        "anti_pattern_warnings": [
          "do_not_hide_verification_paths_only_in_runbooks",
          "do_not_force_agents_to_guess_the_post_deploy_check"
        ],
        "expected_glue_reduction": {
          "orchestration": [
            "post_deploy_verification_wrapper_logic",
            "runbook_only_follow_up_guidance"
          ],
          "observability": [
            "manual_write_then_check_reconstruction"
          ]
        }
      }
    },
    "scenario": {
      "scenario": {
        "name": "deploy_service_then_verify_status_path",
        "category": "orchestration",
        "narrative": "An agent deploys a service successfully. The next sensible move is usually to verify rollout status using a separate read capability. The interface should make that relationship visible so the agent does not rely on docs, prompt instructions, or wrapper-side maps to know how to verify success.\n",
        "context": {
          "write_capability": "deploy_service",
          "verification_capability": "get_deployment_status",
          "side_effect": "transactional",
          "token_scope": [
            "deploy:write",
            "deploy:read"
          ],
          "task_id": "deploy-verify-2026-04",
          "client_reference_id": "step-9-verify",
          "parent_invocation_id": "inv-deploy-verify-001"
        },
        "expected_behavior": [
          "execute_deploy_with_lineage",
          "make_the_verification_path_discoverable",
          "preserve_lineage_between_write_and_verify",
          "produce_useful_audit_entries_for_both_steps"
        ],
        "expected_anip_support": [
          "task_id_support",
          "parent_invocation_id_support",
          "audit_queryability",
          "follow_up_guidance",
          "verification_path_guidance"
        ]
      }
    },
    "evaluation": null
  },
  {
    "meta": {
      "id": "devops-wait-single",
      "name": "devops-rollout-service",
      "domain": "devops",
      "category": "orchestration",
      "narrative": "An agent attempts to deploy a service during a temporary rollout freeze. The operation should not fail as a generic error and force wrapper-side guesswork. The interface should make it clear that t...",
      "result": null,
      "isMultiService": false
    },
    "requirements": {
      "system": {
        "name": "devops-rollout-service",
        "domain": "devops",
        "deployment_intent": "internal_control_surface"
      },
      "transports": {
        "http": true,
        "stdio": false,
        "grpc": false
      },
      "trust": {
        "mode": "signed",
        "checkpoints": false
      },
      "auth": {
        "delegation_tokens": true,
        "purpose_binding": true,
        "scoped_authority": true
      },
      "permissions": {
        "preflight_discovery": true,
        "restricted_vs_denied": true
      },
      "audit": {
        "durable": true,
        "searchable": true
      },
      "lineage": {
        "invocation_id": true,
        "client_reference_id": true,
        "task_id": true,
        "parent_invocation_id": true
      },
      "risk_profile": {
        "capabilities": {
          "deploy_service": {
            "side_effect": "reversible",
            "recovery_guidance_required": true
          }
        }
      },
      "business_constraints": {
        "temporary_rollout_blocks_should_not_trigger_blind_retry_loops": true,
        "wait_posture_should_be_machine_visible": true
      },
      "scale": {
        "shape_preference": "production_single_service",
        "high_availability": false
      }
    },
    "proposal": {
      "proposal": {
        "recommended_shape": "production_single_service",
        "rationale": [
          "one internal control surface is sufficient",
          "the key issue is reliable wait-and-retry guidance",
          "audit and lineage remain necessary for operator reconstruction"
        ],
        "required_components": [
          "capability_registry",
          "manifest_generator",
          "token_verifier",
          "delegation_engine",
          "permission_evaluator",
          "invocation_executor",
          "failure_mapper",
          "durable_audit_store",
          "lineage_recorder",
          "http_adapter"
        ],
        "optional_components": [
          "token_issuer",
          "embedded_studio"
        ],
        "key_runtime_requirements": [
          "expose temporary unavailability with canonical wait posture",
          "preserve lineage across retry windows",
          "avoid forcing wrapper-side retry classification"
        ],
        "anti_pattern_warnings": [
          "do_not_encode_wait_logic_only_in_clients",
          "do_not_force_agents_to_parse_rate_limit_text"
        ],
        "expected_glue_reduction": {
          "orchestration": [
            "wait_loop_wrapper_logic",
            "temporary_unavailability_retry_rules"
          ],
          "observability": [
            "rollout_retry_chain_reconstruction"
          ]
        }
      }
    },
    "scenario": {
      "scenario": {
        "name": "deploy_service_temporarily_unavailable_wait_path",
        "category": "orchestration",
        "narrative": "An agent attempts to deploy a service during a temporary rollout freeze. The operation should not fail as a generic error and force wrapper-side guesswork. The interface should make it clear that the correct next move is to wait and retry rather than escalate or replan.\n",
        "context": {
          "capability": "deploy_service",
          "side_effect": "transactional",
          "temporary_block_reason": "rollout_window_lock",
          "token_scope": [
            "deploy:write"
          ],
          "task_id": "deploy-release-2026-04",
          "client_reference_id": "step-8-deploy",
          "parent_invocation_id": "inv-rollout-wait-001"
        },
        "expected_behavior": [
          "do_not_execute_blind_retry_loop",
          "explain_that_wait_is_the_correct_recovery_path",
          "preserve_lineage_across_retries",
          "produce_audit_entries_for_failed_attempts"
        ],
        "expected_anip_support": [
          "structured_failure",
          "recovery_class",
          "estimated_availability_support",
          "task_id_support",
          "parent_invocation_id_support",
          "audit_queryability"
        ]
      }
    },
    "evaluation": null
  },
  {
    "meta": {
      "id": "manifest-revalidate-single",
      "name": "api-integration-service",
      "domain": "platform_ops",
      "category": "orchestration",
      "narrative": "An agent attempts an operation using a cached understanding of the service manifest or capability shape. The service state has changed. The interface should make clear that the right move is to rev...",
      "result": null,
      "isMultiService": false
    },
    "requirements": {
      "system": {
        "name": "api-integration-service",
        "domain": "platform_ops",
        "deployment_intent": "internal_control_surface"
      },
      "transports": {
        "http": true,
        "stdio": false,
        "grpc": false
      },
      "trust": {
        "mode": "signed",
        "checkpoints": false
      },
      "auth": {
        "delegation_tokens": true,
        "purpose_binding": true,
        "scoped_authority": true
      },
      "permissions": {
        "preflight_discovery": true,
        "restricted_vs_denied": true
      },
      "audit": {
        "durable": true,
        "searchable": true
      },
      "lineage": {
        "invocation_id": true,
        "client_reference_id": true,
        "task_id": true,
        "parent_invocation_id": true
      },
      "risk_profile": {
        "capabilities": {
          "sync_partner_account": {
            "side_effect": "reversible",
            "recovery_guidance_required": true
          }
        }
      },
      "business_constraints": {
        "stale_manifest_assumptions_should_not_trigger_blind_retry": true,
        "revalidation_path_should_be_clear": true
      },
      "scale": {
        "shape_preference": "production_single_service",
        "high_availability": false
      }
    },
    "proposal": {
      "proposal": {
        "recommended_shape": "production_single_service",
        "rationale": [
          "one service boundary is enough",
          "the primary risk is stale local assumptions about service state",
          "recovery should emphasize revalidation instead of manual debugging"
        ],
        "required_components": [
          "capability_registry",
          "manifest_generator",
          "token_verifier",
          "delegation_engine",
          "permission_evaluator",
          "invocation_executor",
          "failure_mapper",
          "durable_audit_store",
          "lineage_recorder",
          "http_adapter"
        ],
        "optional_components": [
          "token_issuer",
          "embedded_studio"
        ],
        "key_runtime_requirements": [
          "expose state-revalidation failures clearly",
          "point callers toward manifest refresh or equivalent revalidation",
          "preserve task and invocation lineage through correction loops"
        ],
        "anti_pattern_warnings": [
          "do_not_hide_manifest_drift_only_in_transport_errors",
          "do_not_force_manual_cache_invalidation_guesswork"
        ],
        "expected_glue_reduction": {
          "orchestration": [
            "manifest_refresh_wrapper_logic",
            "stale_assumption_recovery_glue"
          ],
          "observability": [
            "debug_only_revalidation_paths"
          ]
        }
      }
    },
    "scenario": {
      "scenario": {
        "name": "stale_manifest_requires_revalidation_before_retry",
        "category": "orchestration",
        "narrative": "An agent attempts an operation using a cached understanding of the service manifest or capability shape. The service state has changed. The interface should make clear that the right move is to revalidate state before retrying, rather than blindly retrying or escalating.\n",
        "context": {
          "capability": "sync_partner_account",
          "stale_local_artifact": "cached_manifest",
          "side_effect": "transactional",
          "token_scope": [
            "partners:sync"
          ],
          "task_id": "partner-sync-2026-04",
          "client_reference_id": "step-2-sync",
          "parent_invocation_id": "inv-manifest-drift-001"
        },
        "expected_behavior": [
          "do_not_retry_blindly",
          "explain_that_revalidation_is_required",
          "make_the_revalidation_path_clear",
          "preserve_lineage_across_retry_after_revalidation",
          "produce_audit_entries_for_failed_and_retried_steps"
        ],
        "expected_anip_support": [
          "structured_failure",
          "recovery_class",
          "revalidation_guidance",
          "task_id_support",
          "parent_invocation_id_support",
          "audit_queryability"
        ]
      }
    },
    "evaluation": null
  },
  {
    "meta": {
      "id": "order-async-followup-multiservice",
      "name": "order-followup-estate",
      "domain": "commerce",
      "category": "observability",
      "narrative": "An order is submitted on one service and, after a delay, fulfillment status is checked on another service. The lineage should remain legible enough that operators and agents do not need hidden sche...",
      "result": null,
      "isMultiService": true
    },
    "requirements": {
      "system": {
        "name": "order-followup-estate",
        "domain": "commerce",
        "deployment_intent": "multi_service_agent_execution"
      },
      "services": [
        {
          "name": "order-service",
          "role": "execution",
          "public_http": true
        },
        {
          "name": "fulfillment-service",
          "role": "followup",
          "public_http": true
        }
      ],
      "transports": {
        "http": true,
        "stdio": false,
        "grpc": false
      },
      "trust": {
        "mode": "signed",
        "checkpoints": false
      },
      "auth": {
        "delegation_tokens": true,
        "purpose_binding": true,
        "scoped_authority": true,
        "service_to_service_handoffs": true
      },
      "permissions": {
        "preflight_discovery": true,
        "restricted_vs_denied": true
      },
      "audit": {
        "durable": true,
        "searchable": true,
        "cross_service_reconstruction_required": true
      },
      "lineage": {
        "invocation_id": true,
        "client_reference_id": true,
        "task_id": true,
        "parent_invocation_id": true,
        "cross_service_continuity_required": true
      },
      "business_constraints": {
        "delayed_cross_service_followups_should_still_be_legible": true,
        "async_steps_should_not_require_hidden_parent_link_rules": true
      },
      "scale": {
        "shape_preference": "multi_service_estate",
        "high_availability": false
      }
    },
    "proposal": {
      "proposal": {
        "recommended_shape": "multi_service_estate",
        "rationale": [
          "the downstream action happens later on a different service",
          "continuity survives, but interpretation of delayed follow-up still needs explicit pressure"
        ],
        "required_components": [
          "manifest_generator_per_service",
          "token_verifier_per_service",
          "invocation_executor_per_service",
          "durable_audit_store_per_service",
          "lineage_recorder_per_service",
          "bounded_async_followup_guidance"
        ],
        "anti_pattern_warnings": [
          "do_not_drop_lineage_on_delayed_followups",
          "do_not_require_hidden_scheduler_specific_linkage_rules"
        ],
        "expected_glue_reduction": {
          "orchestration": [
            "delayed_followup_parent_link_glue"
          ],
          "observability": [
            "async_cross_service_reconstruction_guesswork"
          ]
        }
      }
    },
    "scenario": {
      "scenario": {
        "name": "delayed_fulfillment_check_links_back_to_original_order",
        "category": "observability",
        "narrative": "An order is submitted on one service and, after a delay, fulfillment status is checked on another service. The lineage should remain legible enough that operators and agents do not need hidden scheduler-specific conventions to understand the relationship.\n",
        "context": {
          "execution_service_capability": "submit_order",
          "followup_service_capability": "check_fulfillment",
          "task_id": "order-followup-2026-04",
          "parent_order_invocation_id": "inv-order-001",
          "delayed_followup": true
        },
        "expected_behavior": [
          "delayed_downstream_step_preserves_task_identity",
          "parent_link_remains_legible_across_time_gap",
          "operator_can_reconstruct_the_two_service_chain"
        ],
        "expected_anip_support": [
          "task_id_support",
          "parent_invocation_id_support",
          "audit_queryability",
          "cross_service_reconstruction_guidance"
        ]
      }
    },
    "evaluation": null
  },
  {
    "meta": {
      "id": "travel-followup-multiservice",
      "name": "travel-booking-estate-followup",
      "domain": "travel",
      "category": "orchestration",
      "narrative": "An agent searches flights in one service, books the selected flight in a second service, and then needs to confirm booking status through a third service. The system should make the likely follow-u...",
      "result": null,
      "isMultiService": true
    },
    "requirements": {
      "system": {
        "name": "travel-booking-estate-followup",
        "domain": "travel",
        "deployment_intent": "multi_service_agent_execution"
      },
      "services": [
        {
          "name": "travel-search",
          "role": "planning",
          "public_http": true
        },
        {
          "name": "travel-booking",
          "role": "execution",
          "public_http": true
        },
        {
          "name": "travel-status",
          "role": "verification",
          "public_http": true
        }
      ],
      "transports": {
        "http": true,
        "stdio": false,
        "grpc": false
      },
      "trust": {
        "mode": "signed",
        "checkpoints": false
      },
      "auth": {
        "delegation_tokens": true,
        "purpose_binding": true,
        "scoped_authority": true,
        "service_to_service_handoffs": true
      },
      "permissions": {
        "preflight_discovery": true,
        "restricted_vs_denied": true,
        "grantable_requirements": true
      },
      "audit": {
        "durable": true,
        "searchable": true,
        "cross_service_reconstruction_required": true
      },
      "lineage": {
        "invocation_id": true,
        "client_reference_id": true,
        "task_id": true,
        "parent_invocation_id": true,
        "cross_service_continuity_required": true
      },
      "risk_profile": {
        "service_a": {
          "search_flights": {
            "side_effect": "none"
          }
        },
        "service_b": {
          "book_flight": {
            "side_effect": "irreversible",
            "cost_visibility_required": true,
            "recovery_guidance_required": true
          }
        },
        "service_c": {
          "get_booking_status": {
            "side_effect": "none"
          }
        }
      },
      "business_constraints": {
        "cross_service_follow_up_paths_should_be_discoverable": true,
        "booking_result_should_be_verifiable_without_wrapper_side_maps": true,
        "action_chain_must_remain_reconstructable": true
      },
      "scale": {
        "shape_preference": "multi_service_estate",
        "high_availability": false
      }
    },
    "proposal": {
      "proposal": {
        "recommended_shape": "multi_service_estate",
        "rationale": [
          "planning, booking, and verification are split across service boundaries",
          "each service needs its own audit integrity",
          "cross-service follow-up discovery is the main new problem"
        ],
        "service_shapes": {
          "travel-search": {
            "shape": "production_single_service"
          },
          "travel-booking": {
            "shape": "production_single_service"
          },
          "travel-status": {
            "shape": "production_single_service"
          }
        },
        "shared_requirements": [
          "task_id propagation across services",
          "parent_invocation_id propagation across service hops",
          "durable audit in all services",
          "searchable audit in all services",
          "discoverable follow-up and verification relationships"
        ],
        "required_components": [
          "manifest_generator_per_service",
          "token_verifier_per_service",
          "permission_evaluator_per_service",
          "invocation_executor_per_service",
          "failure_mapper_per_service",
          "durable_audit_store_per_service",
          "lineage_recorder_per_service",
          "handoff_propagation_rules"
        ],
        "optional_components": [
          "central_aggregated_lineage_index",
          "shared_search_layer_for_operator_views",
          "approval_service"
        ],
        "key_runtime_requirements": [
          "search results should be linkable to booking actions",
          "booking actions should have a discoverable verification path",
          "task identity should survive across planning, execution, and verification",
          "each service should remain independently auditable"
        ],
        "anti_pattern_warnings": [
          "do_not_hide_cross_service_next_steps_only_in_wrapper_code",
          "do_not_push_follow_up_relationships_only_into_docs",
          "do_not_make_verification_depend_on_out_of_band_operator_knowledge"
        ],
        "expected_glue_reduction": {
          "orchestration": [
            "cross_service_next_step_wrapper_logic",
            "post_booking_verification_mapping"
          ],
          "observability": [
            "workflow_reconstruction_across_three_services",
            "operator_side_follow_up_guesswork"
          ]
        }
      }
    },
    "scenario": {
      "scenario": {
        "name": "search_book_verify_across_services_with_discoverable_followup",
        "category": "orchestration",
        "narrative": "An agent searches flights in one service, books the selected flight in a second service, and then needs to confirm booking status through a third service. The system should make the likely follow-up and verification path visible without requiring wrapper-side maps or UI-only journey knowledge.\n",
        "context": {
          "planning_service_capability": "search_flights",
          "execution_service_capability": "book_flight",
          "verification_service_capability": "get_booking_status",
          "side_effect_execution": "irreversible",
          "task_id": "trip-followup-2026-04",
          "parent_search_invocation_id": "inv-followup-search-001",
          "token_scope_service_a": [
            "flights:search"
          ],
          "token_scope_service_b": [
            "flights:book"
          ],
          "token_scope_service_c": [
            "bookings:read"
          ]
        },
        "expected_behavior": [
          "search_service_returns_candidates",
          "booking_service_receives_lineage",
          "verification_path_is_discoverable_after_booking",
          "cross_service_task_identity_is_preserved",
          "operator_can_reconstruct_the_three_step_chain"
        ],
        "expected_anip_support": [
          "task_id_support",
          "parent_invocation_id_support",
          "structured_failure",
          "audit_queryability",
          "follow_up_guidance",
          "verification_path_guidance"
        ]
      }
    },
    "evaluation": null
  },
  {
    "meta": {
      "id": "travel-multiservice",
      "name": "travel-multiservice-estate",
      "domain": "travel",
      "category": "orchestration",
      "narrative": "An agent searches for flights in the search service, selects the cheapest viable result, then attempts to book that flight through the booking service. The chosen option costs 800 USD while the use...",
      "result": "PARTIAL",
      "isMultiService": true
    },
    "requirements": {
      "system": {
        "name": "travel-multiservice-estate",
        "domain": "travel",
        "deployment_intent": "multi_service_agent_execution"
      },
      "services": [
        {
          "name": "travel-search",
          "role": "planning",
          "public_http": true
        },
        {
          "name": "travel-booking",
          "role": "execution",
          "public_http": true
        }
      ],
      "transports": {
        "http": true,
        "stdio": false,
        "grpc": false
      },
      "trust": {
        "mode": "signed",
        "checkpoints": false
      },
      "auth": {
        "delegation_tokens": true,
        "purpose_binding": true,
        "scoped_authority": true,
        "service_to_service_handoffs": true
      },
      "permissions": {
        "preflight_discovery": true,
        "restricted_vs_denied": true,
        "grantable_requirements": true
      },
      "audit": {
        "durable": true,
        "searchable": true,
        "cross_service_reconstruction_required": true
      },
      "lineage": {
        "invocation_id": true,
        "client_reference_id": true,
        "task_id": true,
        "parent_invocation_id": true,
        "cross_service_continuity_required": true
      },
      "risk_profile": {
        "service_a": {
          "search_flights": {
            "side_effect": "none"
          }
        },
        "service_b": {
          "book_flight": {
            "side_effect": "irreversible",
            "cost_visibility_required": true,
            "recovery_guidance_required": true
          }
        }
      },
      "business_constraints": {
        "agent_must_compare_before_booking": true,
        "booking_budget_limit_required": true,
        "booking_service_must_be_auditable_independently": true,
        "cross_service_action_chain_must_be_reconstructable": true
      },
      "scale": {
        "shape_preference": "multi_service_estate",
        "high_availability": false
      }
    },
    "proposal": {
      "proposal": {
        "recommended_shape": "multi_service_estate",
        "rationale": [
          "planning and booking are split across service boundaries",
          "each service needs its own audit integrity",
          "cross-service lineage is a hard requirement",
          "one monolith would reduce realism and hide the handoff problem"
        ],
        "service_shapes": {
          "travel-search": {
            "shape": "production_single_service"
          },
          "travel-booking": {
            "shape": "production_single_service"
          }
        },
        "shared_requirements": [
          "task_id propagation across services",
          "parent_invocation_id propagation across service hops",
          "durable audit in both services",
          "searchable audit in both services",
          "consistent delegation and purpose semantics"
        ],
        "required_components": [
          "manifest_generator_per_service",
          "token_verifier_per_service",
          "permission_evaluator_per_service",
          "invocation_executor_per_service",
          "failure_mapper_per_service",
          "durable_audit_store_per_service",
          "lineage_recorder_per_service",
          "handoff_propagation_rules"
        ],
        "optional_components": [
          "shared_search_layer_for_audit_views",
          "central_aggregated_lineage_index",
          "external_policy_service",
          "approval_service"
        ],
        "key_runtime_requirements": [
          "search results should be linkable to later booking actions",
          "booking failures should preserve parent invocation lineage",
          "task identity should survive cross-service execution",
          "each service should remain independently auditable"
        ],
        "anti_pattern_warnings": [
          "do_not_rely_on_custom_headers_as_the_primary_lineage_surface",
          "do_not_push_cross_service_correlation_only_into_logs",
          "do_not_make_booking_service_depend_on_search_service_local_state",
          "do_not_hide_handoff_logic_only_in_wrapper_code"
        ],
        "expected_glue_reduction": {
          "safety": [
            "cross_service_permission_probe_glue",
            "invoke_then_fail_booking_glue"
          ],
          "orchestration": [
            "planning_to_booking_wrapper_glue",
            "parent_child_handoff_glue"
          ],
          "observability": [
            "cross_service_trace_stitching",
            "workflow_reconstruction_across_services"
          ]
        }
      }
    },
    "scenario": {
      "scenario": {
        "name": "search_then_book_across_services_with_budget_constraint",
        "category": "orchestration",
        "narrative": "An agent searches for flights in the search service, selects the cheapest viable result, then attempts to book that flight through the booking service. The chosen option costs 800 USD while the user's practical budget limit is 500 USD. The system must preserve task identity and parent/child invocation lineage across the service boundary.\n",
        "context": {
          "task_id": "trip-q2-customer-42",
          "parent_search_invocation_id": "inv-a1b2c3d4e5f6",
          "selected_capability_service_a": "search_flights",
          "selected_capability_service_b": "book_flight",
          "selected_flight": "DL310",
          "selected_cost": 800,
          "budget_limit": 500,
          "token_scope_service_a": [
            "flights:search"
          ],
          "token_scope_service_b": [
            "flights:book"
          ],
          "side_effect_service_b": "irreversible"
        },
        "expected_behavior": [
          "search_service_returns_candidates",
          "booking_service_receives_task_identity",
          "booking_service_receives_parent_invocation_lineage",
          "system_does_not_execute_blindly_if_budget_control_exists",
          "both_services_produce_useful_audit_entries",
          "operator_can_reconstruct_the_cross_service_chain"
        ],
        "expected_anip_support": [
          "permission_discovery",
          "side_effect_visibility",
          "cost_visibility",
          "task_id_support",
          "parent_invocation_id_support",
          "audit_queryability",
          "structured_failure"
        ]
      }
    },
    "evaluation": {
      "evaluation": {
        "scenario_name": "search_then_book_across_services_with_budget_constraint",
        "result": "PARTIAL",
        "handled_by_anip": [
          "cross-service task identity continuity",
          "parent invocation lineage",
          "independent but linkable audit records",
          "cleaner planning-to-booking handoff",
          "structured failure surfaces"
        ],
        "glue_you_will_still_write": [
          "you will still write budget-enforcement logic in the booking service, because the constraint is not yet enforced through delegation or permissions",
          "you will still write some organization-specific handoff policy logic here",
          "you may still write a cross-service audit aggregation layer here"
        ],
        "glue_category": [
          "safety",
          "orchestration",
          "observability"
        ],
        "why": [
          "the design removes a large amount of cross-service correlation and trace-stitching glue",
          "task and parent invocation continuity are materially improved across the service boundary",
          "the budget-control requirement is still not encoded as an enforceable ANIP-visible control surface in the booking path"
        ],
        "what_would_improve": [
          "represent budget as enforceable authority or policy in the booking path",
          "expose budget-based blocking through permissions or structured invoke failure",
          "add easier cross-service lineage query support for operators"
        ],
        "confidence": "high"
      }
    }
  },
  {
    "meta": {
      "id": "travel-quote-handoff-multiservice",
      "name": "travel-quote-handoff-estate",
      "domain": "travel",
      "category": "orchestration",
      "narrative": "A search service returns a priced quote artifact and a booking service must consume it. The system should make the cross-service handoff semantically legible enough that the agent does not rely on ...",
      "result": null,
      "isMultiService": true
    },
    "requirements": {
      "system": {
        "name": "travel-quote-handoff-estate",
        "domain": "travel",
        "deployment_intent": "multi_service_agent_execution"
      },
      "services": [
        {
          "name": "travel-search",
          "role": "planning",
          "public_http": true
        },
        {
          "name": "travel-booking",
          "role": "execution",
          "public_http": true
        }
      ],
      "transports": {
        "http": true,
        "stdio": false,
        "grpc": false
      },
      "trust": {
        "mode": "signed",
        "checkpoints": false
      },
      "auth": {
        "delegation_tokens": true,
        "purpose_binding": true,
        "scoped_authority": true,
        "service_to_service_handoffs": true
      },
      "permissions": {
        "preflight_discovery": true,
        "restricted_vs_denied": true
      },
      "audit": {
        "durable": true,
        "searchable": true,
        "cross_service_reconstruction_required": true
      },
      "lineage": {
        "invocation_id": true,
        "client_reference_id": true,
        "task_id": true,
        "parent_invocation_id": true,
        "cross_service_continuity_required": true
      },
      "risk_profile": {
        "planning_service": {
          "search_flights": {
            "side_effect": "none"
          }
        },
        "execution_service": {
          "book_flight": {
            "side_effect": "irreversible",
            "recovery_guidance_required": true
          }
        }
      },
      "business_constraints": {
        "quote_handoff_should_not_depend_on_wrapper_only_contracts": true,
        "downstream_service_should_not_need_ui_only_context_to_use_upstream_output": true,
        "cross_service_booking_chain_must_be_reconstructable": true,
        "upstream_quote_should_be_machine_usable_by_downstream_service": true
      },
      "scale": {
        "shape_preference": "multi_service_estate",
        "high_availability": false
      }
    },
    "proposal": {
      "proposal": {
        "recommended_shape": "multi_service_estate",
        "rationale": [
          "search and booking remain split across service boundaries",
          "the main gap is not continuity alone but quote handoff meaning",
          "operators still need both services independently auditable"
        ],
        "service_shapes": {
          "travel-search": {
            "shape": "production_single_service"
          },
          "travel-booking": {
            "shape": "production_single_service"
          }
        },
        "shared_requirements": [
          "task_id propagation across services",
          "parent_invocation_id propagation across service hops",
          "durable audit in both services",
          "explicit cross-service artifact handoff semantics"
        ],
        "required_components": [
          "manifest_generator_per_service",
          "token_verifier_per_service",
          "permission_evaluator_per_service",
          "invocation_executor_per_service",
          "failure_mapper_per_service",
          "durable_audit_store_per_service",
          "lineage_recorder_per_service",
          "bounded_handoff_semantics"
        ],
        "optional_components": [
          "central_aggregated_lineage_index",
          "operator_search_overlay"
        ],
        "key_runtime_requirements": [
          "upstream search output should be legible to the downstream booking service",
          "handoff meaning should be visible without bespoke translation rules",
          "continuity should survive the boundary without hiding handoff ambiguity"
        ],
        "anti_pattern_warnings": [
          "do_not_treat_cross_service_outputs_as_self_explanatory",
          "do_not_hide_quote_to_booking_contract_only_in_wrapper_code",
          "do_not_require_ui_journey_knowledge_to_complete_the_handoff"
        ],
        "expected_glue_reduction": {
          "orchestration": [
            "quote_to_booking_translation_glue",
            "service_boundary_handoff_guesswork"
          ],
          "observability": [
            "operator_side_handoff_reconstruction_guesswork"
          ]
        }
      }
    },
    "scenario": {
      "scenario": {
        "name": "quote_handoff_from_search_service_to_booking_service",
        "category": "orchestration",
        "narrative": "A search service returns a priced quote artifact and a booking service must consume it. The system should make the cross-service handoff semantically legible enough that the agent does not rely on bespoke wrapper contracts to know how the downstream booking action relates to the upstream quote.\n",
        "context": {
          "planning_service_capability": "search_flights",
          "execution_service_capability": "book_flight",
          "upstream_artifact": "priced_quote",
          "side_effect_execution": "irreversible",
          "task_id": "trip-handoff-2026-04",
          "parent_search_invocation_id": "inv-quote-handoff-001",
          "token_scope_service_a": [
            "flights:search"
          ],
          "token_scope_service_b": [
            "flights:book"
          ]
        },
        "expected_behavior": [
          "search_service_returns_quote_artifact",
          "booking_service_receives_cross_service_lineage",
          "handoff_meaning_is_more_explicit_than_a_raw_object_pass",
          "operator_can_reconstruct_the_cross_service_booking_chain"
        ],
        "expected_anip_support": [
          "task_id_support",
          "parent_invocation_id_support",
          "audit_queryability",
          "cross_service_handoff_guidance"
        ]
      }
    },
    "evaluation": null
  },
  {
    "meta": {
      "id": "travel-refresh-handoff-multiservice",
      "name": "travel-refresh-handoff-estate",
      "domain": "travel",
      "category": "orchestration",
      "narrative": "A booking service rejects an upstream quote because it is stale. The agent now needs to know which upstream service and capability should be invoked to refresh the artifact before retrying, without...",
      "result": null,
      "isMultiService": true
    },
    "requirements": {
      "system": {
        "name": "travel-refresh-handoff-estate",
        "domain": "travel",
        "deployment_intent": "multi_service_agent_execution"
      },
      "services": [
        {
          "name": "travel-search",
          "role": "planning",
          "public_http": true
        },
        {
          "name": "travel-booking",
          "role": "execution",
          "public_http": true
        }
      ],
      "transports": {
        "http": true,
        "stdio": false,
        "grpc": false
      },
      "trust": {
        "mode": "signed",
        "checkpoints": false
      },
      "auth": {
        "delegation_tokens": true,
        "purpose_binding": true,
        "scoped_authority": true,
        "service_to_service_handoffs": true
      },
      "permissions": {
        "preflight_discovery": true,
        "restricted_vs_denied": true
      },
      "audit": {
        "durable": true,
        "searchable": true,
        "cross_service_reconstruction_required": true
      },
      "lineage": {
        "invocation_id": true,
        "client_reference_id": true,
        "task_id": true,
        "parent_invocation_id": true,
        "cross_service_continuity_required": true
      },
      "risk_profile": {
        "planning_service": {
          "search_flights": {
            "side_effect": "none"
          }
        },
        "execution_service": {
          "book_flight": {
            "side_effect": "irreversible",
            "recovery_guidance_required": true
          }
        }
      },
      "business_constraints": {
        "stale_cross_service_artifacts_should_not_force_manual_wrapper_logic": true,
        "refresh_source_should_be_discoverable_across_service_boundary": true,
        "upstream_artifacts_may_expire_before_downstream_use": true
      },
      "scale": {
        "shape_preference": "multi_service_estate",
        "high_availability": false
      }
    },
    "proposal": {
      "proposal": {
        "recommended_shape": "multi_service_estate",
        "rationale": [
          "the refresh source lives on a different service than the failing action",
          "continuity alone is not enough when the upstream artifact goes stale",
          "the main new problem is distributed refresh-path clarity"
        ],
        "service_shapes": {
          "travel-search": {
            "shape": "production_single_service"
          },
          "travel-booking": {
            "shape": "production_single_service"
          }
        },
        "shared_requirements": [
          "cross-service continuity",
          "durable audit in both services",
          "refresh-source discoverability across the service boundary"
        ],
        "required_components": [
          "manifest_generator_per_service",
          "token_verifier_per_service",
          "invocation_executor_per_service",
          "failure_mapper_per_service",
          "durable_audit_store_per_service",
          "lineage_recorder_per_service",
          "bounded_cross_service_refresh_guidance"
        ],
        "anti_pattern_warnings": [
          "do_not_hide_refresh_source_only_in_ops_runbooks",
          "do_not_force_agents_to_infer_cross_service_refresh_paths_from_names"
        ],
        "expected_glue_reduction": {
          "orchestration": [
            "stale_quote_refresh_mapping_glue",
            "cross_service_retry_source_guesswork"
          ]
        }
      }
    },
    "scenario": {
      "scenario": {
        "name": "stale_quote_requires_cross_service_refresh_before_booking",
        "category": "orchestration",
        "narrative": "A booking service rejects an upstream quote because it is stale. The agent now needs to know which upstream service and capability should be invoked to refresh the artifact before retrying, without relying on wrapper-side maps.\n",
        "context": {
          "planning_service_capability": "search_flights",
          "execution_service_capability": "book_flight",
          "failure_type": "binding_stale",
          "task_id": "trip-refresh-2026-04",
          "parent_search_invocation_id": "inv-refresh-001",
          "token_scope_service_a": [
            "flights:search"
          ],
          "token_scope_service_b": [
            "flights:book"
          ]
        },
        "expected_behavior": [
          "booking_service_preserves_cross_service_lineage",
          "refresh_source_is_discoverable_without_bespoke_glue",
          "operator_can_link_the_failed_booking_back_to_the_search_step"
        ],
        "expected_anip_support": [
          "task_id_support",
          "parent_invocation_id_support",
          "structured_failure",
          "audit_queryability",
          "cross_service_refresh_guidance"
        ]
      }
    },
    "evaluation": null
  },
  {
    "meta": {
      "id": "travel-refresh-single",
      "name": "travel-booking-service-refresh",
      "domain": "travel",
      "category": "orchestration",
      "narrative": "An agent attempts to book a flight using a quote obtained earlier in the task. The quote is now stale. The system should not just say \"refresh required\" — it should make the refresh path itself dis...",
      "result": null,
      "isMultiService": false
    },
    "requirements": {
      "system": {
        "name": "travel-booking-service-refresh",
        "domain": "travel",
        "deployment_intent": "public_http_service"
      },
      "transports": {
        "http": true,
        "stdio": false,
        "grpc": false
      },
      "trust": {
        "mode": "signed",
        "checkpoints": false
      },
      "auth": {
        "delegation_tokens": true,
        "purpose_binding": true,
        "scoped_authority": true
      },
      "permissions": {
        "preflight_discovery": true,
        "restricted_vs_denied": true
      },
      "audit": {
        "durable": true,
        "searchable": true
      },
      "lineage": {
        "invocation_id": true,
        "client_reference_id": true,
        "task_id": true,
        "parent_invocation_id": true
      },
      "risk_profile": {
        "capabilities": {
          "search_flights": {
            "side_effect": "none"
          },
          "book_flight": {
            "side_effect": "irreversible",
            "cost_visibility_required": true,
            "recovery_guidance_required": true
          }
        }
      },
      "business_constraints": {
        "stale_quotes_must_not_be_booked": true,
        "refresh_path_should_be_discoverable": true,
        "blocked_booking_should_preserve_lineage": true
      },
      "scale": {
        "shape_preference": "production_single_service",
        "high_availability": false
      }
    },
    "proposal": {
      "proposal": {
        "recommended_shape": "production_single_service",
        "rationale": [
          "quote search and booking can remain in one service",
          "durable audit and lineage remain required",
          "the main problem is refresh-path discoverability, not service partitioning"
        ],
        "required_components": [
          "capability_registry",
          "manifest_generator",
          "token_verifier",
          "delegation_engine",
          "permission_evaluator",
          "invocation_executor",
          "failure_mapper",
          "durable_audit_store",
          "lineage_recorder",
          "http_adapter"
        ],
        "optional_components": [
          "token_issuer",
          "embedded_studio"
        ],
        "key_runtime_requirements": [
          "expose stale-binding failures with explicit recovery posture",
          "expose which capability typically refreshes stale quote state",
          "preserve task and parent invocation lineage through refresh loops"
        ],
        "anti_pattern_warnings": [
          "do_not_hide_quote_refresh_only_in_docs",
          "do_not_make_agents_guess_which_capability_refreshes_a_quote",
          "do_not_push_recovery_sequencing_only_into_prompt_logic"
        ],
        "expected_glue_reduction": {
          "orchestration": [
            "quote_refresh_wrapper_logic",
            "stale_binding_prompt_rules"
          ],
          "safety": [
            "stale_quote_booking_guard_glue"
          ],
          "observability": [
            "retry_chain_reconstruction"
          ]
        }
      }
    },
    "scenario": {
      "scenario": {
        "name": "book_flight_with_stale_quote_needs_refresh_path",
        "category": "orchestration",
        "narrative": "An agent attempts to book a flight using a quote obtained earlier in the task. The quote is now stale. The system should not just say \"refresh required\" — it should make the refresh path itself discoverable so the agent knows that searching flights again is the typical next step.\n",
        "context": {
          "stale_capability": "book_flight",
          "refresh_capability": "search_flights",
          "stale_binding_field": "quote_id",
          "side_effect": "irreversible",
          "token_scope": [
            "flights:search",
            "flights:book"
          ],
          "task_id": "trip-planning-refresh-01",
          "client_reference_id": "step-5-book",
          "parent_invocation_id": "inv-stale-quote-001"
        },
        "expected_behavior": [
          "do_not_execute_with_stale_quote",
          "explain_that_refresh_is_required",
          "make_the_refresh_path_discoverable",
          "preserve_task_identity_across_refresh",
          "preserve_parent_invocation_lineage",
          "produce_audit_entries_for_failed_and_refreshed_steps"
        ],
        "expected_anip_support": [
          "structured_failure",
          "recovery_class",
          "binding_freshness_visibility",
          "refresh_path_guidance",
          "task_id_support",
          "parent_invocation_id_support",
          "audit_queryability"
        ]
      }
    },
    "evaluation": null
  },
  {
    "meta": {
      "id": "travel-single",
      "name": "travel-booking-service",
      "domain": "travel",
      "category": "safety",
      "narrative": "An agent is helping a user plan travel. The user has delegated booking authority, but only within a practical budget boundary of 500 USD. A candidate flight costs 800 USD.",
      "result": "PARTIAL",
      "isMultiService": false
    },
    "requirements": {
      "system": {
        "name": "travel-booking-service",
        "domain": "travel",
        "deployment_intent": "public_http_service"
      },
      "transports": {
        "http": true,
        "stdio": false,
        "grpc": false
      },
      "trust": {
        "mode": "signed",
        "checkpoints": false
      },
      "auth": {
        "delegation_tokens": true,
        "purpose_binding": true,
        "scoped_authority": true
      },
      "permissions": {
        "preflight_discovery": true,
        "restricted_vs_denied": true
      },
      "audit": {
        "durable": true,
        "searchable": true
      },
      "lineage": {
        "invocation_id": true,
        "client_reference_id": true,
        "task_id": true,
        "parent_invocation_id": true
      },
      "risk_profile": {
        "capabilities": {
          "search_flights": {
            "side_effect": "none"
          },
          "book_flight": {
            "side_effect": "irreversible",
            "cost_visibility_required": true,
            "recovery_guidance_required": true
          }
        }
      },
      "business_constraints": {
        "booking_budget_limit_required": true,
        "over_budget_actions_must_not_execute": true,
        "blocked_actions_should_escalate_cleanly": true
      },
      "scale": {
        "shape_preference": "production_single_service",
        "high_availability": false
      }
    },
    "proposal": {
      "proposal": {
        "recommended_shape": "production_single_service",
        "rationale": [
          "public HTTP surface is required",
          "durable audit and searchable execution history are required",
          "signed trust is sufficient; checkpoints are not required",
          "one service boundary is enough for the current domain"
        ],
        "required_components": [
          "capability_registry",
          "manifest_generator",
          "token_verifier",
          "delegation_engine",
          "permission_evaluator",
          "invocation_executor",
          "failure_mapper",
          "durable_audit_store",
          "lineage_recorder",
          "http_adapter"
        ],
        "optional_components": [
          "token_issuer",
          "embedded_studio",
          "graphql_adapter",
          "rest_adapter",
          "mcp_adapter"
        ],
        "key_runtime_requirements": [
          "expose side_effect posture for book_flight",
          "expose cost metadata for book_flight",
          "support permission discovery before invoke",
          "persist invocation_id, client_reference_id, task_id, parent_invocation_id",
          "return structured failures with recovery guidance"
        ],
        "anti_pattern_warnings": [
          "do_not_leave_budget_reasoning_only_in_prompt_logic",
          "do_not_rely_on_invoke_then_fail_as_primary_permission_model",
          "do_not_push_lineage_only_into_logs"
        ],
        "expected_glue_reduction": {
          "safety": [
            "permission_wrapper_glue",
            "invoke_then_fail_budget_glue",
            "blocked_action_recovery_glue"
          ],
          "orchestration": [
            "some_preflight_wrapper_logic"
          ],
          "observability": [
            "correlation_id_stitching",
            "audit_reconstruction_logic"
          ]
        }
      }
    },
    "scenario": {
      "scenario": {
        "name": "book_flight_over_budget",
        "category": "safety",
        "narrative": "An agent is helping a user plan travel. The user has delegated booking authority, but only within a practical budget boundary of 500 USD. A candidate flight costs 800 USD.\n",
        "context": {
          "capability": "book_flight",
          "side_effect": "irreversible",
          "expected_cost": 800,
          "budget_limit": 500,
          "token_scope": [
            "flights:book"
          ],
          "permissions_state": "available",
          "task_id": "trip-planning-q2",
          "client_reference_id": "step-3-book",
          "parent_invocation_id": "inv-a1b2c3d4e5f6"
        },
        "expected_behavior": [
          "do_not_execute",
          "explain_budget_conflict",
          "preserve_task_identity",
          "preserve_parent_invocation_lineage",
          "produce_audit_entry",
          "prefer_escalation_or_replan_over_blind_retry"
        ],
        "expected_anip_support": [
          "cost_visibility",
          "side_effect_visibility",
          "structured_failure",
          "task_id_support",
          "parent_invocation_id_support",
          "audit_queryability"
        ]
      }
    },
    "evaluation": {
      "evaluation": {
        "scenario_name": "book_flight_over_budget",
        "result": "PARTIAL",
        "handled_by_anip": [
          "side-effect visibility",
          "cost visibility",
          "permission discovery",
          "structured failure",
          "task identity",
          "parent invocation lineage",
          "audit recording"
        ],
        "glue_you_will_still_write": [
          "you will still write budget-enforcement logic here unless the budget limit is represented in delegation, permission evaluation, or a protocol-visible control layer",
          "you will still write approval or escalation routing here if the organization requires a human to approve over-budget bookings",
          "you may still write comparison or replanning logic here if the agent must search for cheaper alternatives before escalation"
        ],
        "glue_category": [
          "safety",
          "orchestration"
        ],
        "why": [
          "the design improves the decision surface substantially before action",
          "the budget constraint is not yet clearly enforceable through an ANIP-visible control surface",
          "the system is better informed, but still depends on non-ANIP logic for the final guarantee"
        ],
        "what_would_improve": [
          "represent budget as part of enforceable authority or purpose binding",
          "expose budget-based blocking in permission discovery or invoke failure semantics",
          "make the over-budget path explicit in the runtime control surface"
        ],
        "confidence": "high"
      }
    }
  },
  {
    "meta": {
      "id": "trip-fanout-multiservice",
      "name": "trip-fanout-estate",
      "domain": "travel",
      "category": "observability",
      "narrative": "One planning invocation triggers three downstream bookings on different services. The system should make the fan-out reconstructable without custom trace-stitching logic and without implying a work...",
      "result": null,
      "isMultiService": true
    },
    "requirements": {
      "system": {
        "name": "trip-fanout-estate",
        "domain": "travel",
        "deployment_intent": "multi_service_agent_execution"
      },
      "services": [
        {
          "name": "trip-planner",
          "role": "planning",
          "public_http": true
        },
        {
          "name": "flight-booking",
          "role": "execution",
          "public_http": true
        },
        {
          "name": "hotel-booking",
          "role": "execution",
          "public_http": true
        },
        {
          "name": "car-booking",
          "role": "execution",
          "public_http": true
        }
      ],
      "transports": {
        "http": true,
        "stdio": false,
        "grpc": false
      },
      "trust": {
        "mode": "signed",
        "checkpoints": false
      },
      "auth": {
        "delegation_tokens": true,
        "purpose_binding": true,
        "scoped_authority": true,
        "service_to_service_handoffs": true
      },
      "permissions": {
        "preflight_discovery": true,
        "restricted_vs_denied": true
      },
      "audit": {
        "durable": true,
        "searchable": true,
        "cross_service_reconstruction_required": true
      },
      "lineage": {
        "invocation_id": true,
        "client_reference_id": true,
        "task_id": true,
        "parent_invocation_id": true,
        "cross_service_continuity_required": true
      },
      "business_constraints": {
        "one_upstream_planning_step_should_link_cleanly_to_multiple_downstream_steps": true,
        "operator_should_reconstruct_fanout_without_custom_trace_joiner": true
      },
      "scale": {
        "shape_preference": "multi_service_estate",
        "high_availability": false
      }
    },
    "proposal": {
      "proposal": {
        "recommended_shape": "multi_service_estate",
        "rationale": [
          "a single planning step fans out into multiple downstream services",
          "continuity is useful here, but the real pressure is reconstructable distributed shape"
        ],
        "required_components": [
          "manifest_generator_per_service",
          "token_verifier_per_service",
          "invocation_executor_per_service",
          "durable_audit_store_per_service",
          "lineage_recorder_per_service",
          "bounded_cross_service_relationship_guidance"
        ],
        "anti_pattern_warnings": [
          "do_not_require_custom_trace_joiners_for_basic_fanout_reconstruction",
          "do_not_hide_fanout_shape_only_in_orchestrator_code"
        ],
        "expected_glue_reduction": {
          "observability": [
            "fanout_trace_stitching_glue",
            "parent_child_tree_reconstruction_guesswork"
          ]
        }
      }
    },
    "scenario": {
      "scenario": {
        "name": "one_planning_step_fans_out_to_multiple_booking_services",
        "category": "observability",
        "narrative": "One planning invocation triggers three downstream bookings on different services. The system should make the fan-out reconstructable without custom trace-stitching logic and without implying a workflow engine.\n",
        "context": {
          "planning_service_capability": "plan_trip",
          "downstream_capabilities": [
            "book_flight",
            "book_hotel",
            "book_car"
          ],
          "task_id": "trip-fanout-2026-04",
          "parent_planning_invocation_id": "inv-fanout-001"
        },
        "expected_behavior": [
          "all_downstream_services_share_task_identity",
          "all_downstream_services_link_back_to_one_parent",
          "operator_can_reconstruct_fanout_shape_from_service_local_audit_logs"
        ],
        "expected_anip_support": [
          "task_id_support",
          "parent_invocation_id_support",
          "audit_queryability",
          "cross_service_reconstruction_guidance"
        ]
      }
    },
    "evaluation": null
  }
]
